// Banco de alimentos — valores médios por 100g, baseados na Tabela TACO
// (UNICAMP/NEPA) e referências USDA para itens não encontrados na TACO.
// Cada alimento aparece uma única vez (um só valor por tipo de preparo).
// kcal=calorias, p=proteína(g), c=carboidrato(g), g=gordura(g), f=fibra(g)

const CATS = {
  favoritos:  { label: "Mais usados",   icon: "🔥" },
  proteina:   { label: "Proteínas",     icon: "🍗" },
  leguminosa: { label: "Leguminosas",   icon: "🫘" },
  carboidrato:{ label: "Carboidratos",  icon: "🍚" },
  gordura:    { label: "Gorduras",      icon: "🥑" },
  fruta:      { label: "Frutas",        icon: "🍌" },
  vegetal:    { label: "Vegetais",      icon: "🥦" },
  laticinio:  { label: "Laticínios",    icon: "🥛" },
  outro:      { label: "Outros",        icon: "🍯" },
  custom:     { label: "Meus alimentos",icon: "⭐" }
};

const MEALS = {
  cafe:   "Café da manhã",
  almoco: "Almoço",
  lanche: "Lanche",
  jantar: "Jantar"
};

const FOODS = [
  // ---------- PROTEÍNAS ----------
  { id:"frango_peito_grelhado", name:"Peito de frango grelhado", cat:"proteina", kcal:159, p:32, c:0, g:2.5, porc:"1 filé médio ≈ 100 g" },
  { id:"frango_peito_cozido", name:"Peito de frango cozido", cat:"proteina", kcal:163, p:31.5, c:0, g:3.2 },
  { id:"frango_coxa_assada", name:"Coxa de frango assada (sem pele)", cat:"proteina", kcal:179, p:26.2, c:0, g:7.9 },
  { id:"carne_patinho_grelhado", name:"Carne bovina (patinho) grelhada", cat:"proteina", kcal:219, p:35.9, c:0, g:7.3 },
  { id:"carne_moida_refogada", name:"Carne moída (patinho) refogada", cat:"proteina", kcal:212, p:26, c:0, g:11.5 },
  { id:"alcatra_grelhada", name:"Alcatra grelhada", cat:"proteina", kcal:175, p:32, c:0, g:5 },
  { id:"lombo_suino_assado", name:"Lombo suíno assado", cat:"proteina", kcal:210, p:31, c:0, g:9 },
  { id:"bacon_frito", name:"Bacon frito", cat:"proteina", kcal:541, p:37, c:1.4, g:42 },
  { id:"presunto_peru", name:"Peito de peru fatiado", cat:"proteina", kcal:110, p:17, c:2, g:3.5 },
  { id:"atum_lata_natural", name:"Atum em lata ao natural (escorrido)", cat:"proteina", kcal:116, p:25.5, c:0, g:0.8 },
  { id:"sardinha_assada", name:"Sardinha assada", cat:"proteina", kcal:164, p:21, c:0, g:8 },
  { id:"salmao_grelhado", name:"Salmão grelhado", cat:"proteina", kcal:243, p:25, c:0, g:15 },
  { id:"tilapia_grelhada", name:"Tilápia grelhada", cat:"proteina", kcal:96, p:20, c:0, g:1.7 },
  { id:"camarao_cozido", name:"Camarão cozido", cat:"proteina", kcal:99, p:24, c:0.2, g:1 },
  { id:"ovo_cozido", name:"Ovo de galinha cozido", cat:"proteina", kcal:146, p:13.3, c:0.6, g:9.5, porc:"1 ovo médio ≈ 50 g" },
  { id:"ovo_frito", name:"Ovo de galinha frito", cat:"proteina", kcal:240, p:15.6, c:1.2, g:18.6 },
  { id:"clara_ovo_cozida", name:"Clara de ovo cozida", cat:"proteina", kcal:52, p:10.9, c:0.7, g:0.2 },
  { id:"tofu_firme", name:"Tofu firme", cat:"proteina", kcal:76, p:8, c:1.9, g:4.8 },
  { id:"whey_concentrado", name:"Whey protein concentrado (pó)", cat:"proteina", kcal:400, p:80, c:7, g:6, porc:"1 dose ≈ 30 g — varia por marca" },

  // ---------- LEGUMINOSAS ----------
  { id:"feijao_carioca_cozido", name:"Feijão carioca cozido", cat:"leguminosa", kcal:76, p:4.8, c:13.6, g:0.5 },
  { id:"feijao_preto_cozido", name:"Feijão preto cozido", cat:"leguminosa", kcal:77, p:4.5, c:14, g:0.5 },
  { id:"lentilha_cozida", name:"Lentilha cozida", cat:"leguminosa", kcal:93, p:6.3, c:16.3, g:0.5 },
  { id:"grao_de_bico_cozido", name:"Grão de bico cozido", cat:"leguminosa", kcal:164, p:8.9, c:27.4, g:2.6 },
  { id:"ervilha_cozida", name:"Ervilha cozida", cat:"leguminosa", kcal:79, p:5.4, c:14.5, g:0.4 },
  { id:"soja_cozida", name:"Soja cozida", cat:"leguminosa", kcal:173, p:18.2, c:9.9, g:9 },

  // ---------- CARBOIDRATOS ----------
  { id:"arroz_branco_cozido", name:"Arroz branco cozido", cat:"carboidrato", kcal:130, p:2.5, c:28.1, g:0.3 },
  { id:"arroz_integral_cozido", name:"Arroz integral cozido", cat:"carboidrato", kcal:124, p:2.6, c:25.8, g:1 },
  { id:"batata_inglesa_cozida", name:"Batata inglesa cozida", cat:"carboidrato", kcal:52, p:1.2, c:11.9, g:0 },
  { id:"batata_doce_cozida", name:"Batata doce cozida", cat:"carboidrato", kcal:77, p:0.6, c:18.4, g:0.1 },
  { id:"mandioca_cozida", name:"Mandioca cozida", cat:"carboidrato", kcal:125, p:0.6, c:30.1, g:0.3 },
  { id:"macarrao_cozido", name:"Macarrão cozido", cat:"carboidrato", kcal:102, p:3.3, c:19.9, g:1.3 },
  { id:"aveia_flocos", name:"Aveia em flocos (crua)", cat:"carboidrato", kcal:394, p:13.9, c:66.6, g:8.5 },
  { id:"pao_frances", name:"Pão francês", cat:"carboidrato", kcal:300, p:8, c:58.7, g:3.1, porc:"1 unidade ≈ 50 g" },
  { id:"pao_forma_integral", name:"Pão de forma integral", cat:"carboidrato", kcal:253, p:9.6, c:49, g:3.5, porc:"1 fatia ≈ 25 g" },
  { id:"tapioca_goma", name:"Tapioca (goma seca)", cat:"carboidrato", kcal:240, p:0.6, c:58.8, g:0.1 },
  { id:"quinoa_cozida", name:"Quinoa cozida", cat:"carboidrato", kcal:120, p:4.4, c:21.3, g:1.9 },
  { id:"milho_verde_cozido", name:"Milho verde cozido", cat:"carboidrato", kcal:98, p:3.4, c:21, g:1 },
  { id:"cuscuz_milho_cozido", name:"Cuscuz de milho cozido", cat:"carboidrato", kcal:112, p:2.5, c:25, g:0.4 },
  { id:"granola", name:"Granola", cat:"carboidrato", kcal:471, p:10, c:64, g:20 },

  // ---------- GORDURAS ----------
  { id:"azeite_oliva", name:"Azeite de oliva extra virgem", cat:"gordura", kcal:884, p:0, c:0, g:100, porc:"1 colher de sopa ≈ 13 g" },
  { id:"oleo_coco", name:"Óleo de coco", cat:"gordura", kcal:862, p:0, c:0, g:99.1 },
  { id:"manteiga", name:"Manteiga", cat:"gordura", kcal:717, p:0.6, c:0.1, g:81 },
  { id:"castanha_para", name:"Castanha-do-pará", cat:"gordura", kcal:656, p:14.5, c:15, g:66.4 },
  { id:"castanha_caju", name:"Castanha de caju", cat:"gordura", kcal:570, p:18.5, c:29, g:46 },
  { id:"amendoim_torrado", name:"Amendoim torrado", cat:"gordura", kcal:544, p:27.2, c:20, g:43.9 },
  { id:"amendoas", name:"Amêndoas", cat:"gordura", kcal:579, p:21.2, c:21.7, g:49.9 },
  { id:"pasta_amendoim", name:"Pasta de amendoim integral", cat:"gordura", kcal:588, p:25, c:20, g:50 },
  { id:"abacate", name:"Abacate", cat:"gordura", kcal:96, p:1.2, c:6, g:8.4 },

  // ---------- FRUTAS ----------
  { id:"banana_prata", name:"Banana prata", cat:"fruta", kcal:98, p:1.3, c:26, g:0.1, porc:"1 unidade ≈ 70 g" },
  { id:"maca", name:"Maçã", cat:"fruta", kcal:56, p:0.3, c:15.2, g:0, porc:"1 unidade ≈ 130 g" },
  { id:"laranja", name:"Laranja", cat:"fruta", kcal:45, p:1, c:11.5, g:0.1 },
  { id:"morango", name:"Morango", cat:"fruta", kcal:30, p:0.9, c:6.8, g:0.3 },
  { id:"mamao", name:"Mamão", cat:"fruta", kcal:40, p:0.5, c:10.4, g:0.1 },
  { id:"manga", name:"Manga", cat:"fruta", kcal:64, p:0.4, c:16.7, g:0.2 },
  { id:"abacaxi", name:"Abacaxi", cat:"fruta", kcal:48, p:0.9, c:12.3, g:0.1 },
  { id:"melancia", name:"Melancia", cat:"fruta", kcal:33, p:0.9, c:8.1, g:0 },
  { id:"uva", name:"Uva", cat:"fruta", kcal:53, p:0.7, c:13.3, g:0.2 },

  // ---------- VEGETAIS ----------
  { id:"brocolis_cozido", name:"Brócolis cozido", cat:"vegetal", kcal:25, p:3.6, c:4, g:0.3 },
  { id:"couve_crua", name:"Couve manteiga crua (picada)", cat:"vegetal", kcal:27, p:2.9, c:4.3, g:0.5 },
  { id:"alface", name:"Alface", cat:"vegetal", kcal:11, p:1.1, c:1.7, g:0.2 },
  { id:"tomate", name:"Tomate", cat:"vegetal", kcal:15, p:1.1, c:3.1, g:0.2 },
  { id:"cenoura_crua", name:"Cenoura crua", cat:"vegetal", kcal:34, p:1.3, c:7.7, g:0.2 },
  { id:"pepino", name:"Pepino", cat:"vegetal", kcal:10, p:0.9, c:2, g:0.1 },
  { id:"cebola_crua", name:"Cebola crua", cat:"vegetal", kcal:39, p:1.7, c:8.9, g:0.1 },
  { id:"pimentao_vermelho", name:"Pimentão vermelho", cat:"vegetal", kcal:21, p:1, c:4.2, g:0.3 },
  { id:"repolho_cru", name:"Repolho cru", cat:"vegetal", kcal:17, p:1.2, c:3.9, g:0.1 },
  { id:"abobrinha_refogada", name:"Abobrinha refogada", cat:"vegetal", kcal:22, p:1.4, c:3.8, g:0.4 },
  { id:"espinafre_refogado", name:"Espinafre refogado", cat:"vegetal", kcal:22, p:2.4, c:2.5, g:1 },
  { id:"vagem_cozida", name:"Vagem cozida", cat:"vegetal", kcal:21, p:1.8, c:4.3, g:0.1 },
  { id:"chuchu_cozido", name:"Chuchu cozido", cat:"vegetal", kcal:17, p:0.6, c:4, g:0.1 },

  // ---------- LATICÍNIOS ----------
  { id:"leite_integral", name:"Leite integral", cat:"laticinio", kcal:61, p:3, c:4.5, g:3.2 },
  { id:"leite_desnatado", name:"Leite desnatado", cat:"laticinio", kcal:35, p:3.4, c:4.9, g:0.2 },
  { id:"iogurte_natural_integral", name:"Iogurte natural integral", cat:"laticinio", kcal:51, p:4.1, c:1.9, g:3 },
  { id:"iogurte_grego", name:"Iogurte grego natural", cat:"laticinio", kcal:97, p:9, c:4, g:5 },
  { id:"queijo_minas_frescal", name:"Queijo minas frescal", cat:"laticinio", kcal:264, p:17.4, c:3.2, g:20 },
  { id:"queijo_mussarela", name:"Queijo muçarela", cat:"laticinio", kcal:330, p:22.6, c:3, g:25.2 },
  { id:"requeijao_cremoso", name:"Requeijão cremoso", cat:"laticinio", kcal:257, p:9.6, c:3, g:23 },

  // ---------- OUTROS ----------
  { id:"mel", name:"Mel", cat:"outro", kcal:309, p:0.4, c:84, g:0 },
  { id:"acucar_refinado", name:"Açúcar refinado", cat:"outro", kcal:387, p:0, c:99.9, g:0 },
  { id:"chocolate_ao_leite", name:"Chocolate ao leite", cat:"outro", kcal:540, p:7.3, c:58, g:30 },
  { id:"whey_isolado", name:"Whey protein isolado (pó)", cat:"outro", kcal:375, p:85, c:3, g:2, porc:"1 dose ≈ 30 g — varia por marca" },

  { id:"arroz_tipo1_cozido", name:"Arroz tipo 1 cozido", cat:"carboidrato", kcal:128, p:2.5, c:28.1, g:0.2 },
  { id:"arroz_tipo2_cozido", name:"Arroz tipo 2 cozido", cat:"carboidrato", kcal:130, p:2.6, c:28.2, g:0.4 },
  { id:"arroz_tipo1_cru", name:"Arroz tipo 1 cru", cat:"carboidrato", kcal:358, p:7.2, c:78.8, g:0.3 },
  { id:"arroz_integral_cru", name:"Arroz integral cru", cat:"carboidrato", kcal:360, p:7.3, c:77.5, g:1.9 },
  { id:"biscoito_maisena", name:"Biscoito maisena", cat:"outro", kcal:443, p:8.1, c:75.2, g:12 },
  { id:"biscoito_recheado_chocolate", name:"Biscoito recheado com chocolate", cat:"outro", kcal:472, p:6.4, c:70.5, g:19.6 },
  { id:"biscoito_recheado_morango", name:"Biscoito recheado com morango", cat:"outro", kcal:471, p:5.7, c:71, g:19.6 },
  { id:"biscoito_wafer_chocolate", name:"Biscoito wafer recheado de chocolate", cat:"outro", kcal:502, p:5.6, c:67.5, g:24.7 },
  { id:"biscoito_wafer_morango", name:"Biscoito wafer recheado de morango", cat:"outro", kcal:513, p:4.5, c:67.4, g:26.4 },
  { id:"cream_cracker", name:"Biscoito salgado cream cracker", cat:"outro", kcal:432, p:10.1, c:68.7, g:14.4 },
  { id:"bolo_mistura", name:"Bolo, mistura para", cat:"outro", kcal:419, p:6.2, c:84.7, g:6.1 },
  { id:"bolo_aipim", name:"Bolo de aipim", cat:"outro", kcal:324, p:4.4, c:47.9, g:12.7 },
  { id:"bolo_chocolate", name:"Bolo de chocolate", cat:"outro", kcal:410, p:6.2, c:54.7, g:18.5 },
  { id:"farinha_centeio_integral", name:"Farinha de centeio integral", cat:"carboidrato", kcal:336, p:12.5, c:73.3, g:1.8 },
  { id:"farinha_milho_amarela", name:"Farinha de milho amarela", cat:"carboidrato", kcal:351, p:7.2, c:79.1, g:1.5 },
  { id:"farinha_rosca", name:"Farinha de rosca", cat:"carboidrato", kcal:371, p:11.4, c:75.8, g:1.5 },
  { id:"farinha_trigo", name:"Farinha de trigo", cat:"carboidrato", kcal:360, p:9.8, c:75.1, g:1.4 },
  { id:"farinha_lactea", name:"Farinha láctea de cereais", cat:"outro", kcal:415, p:11.9, c:77.8, g:5.8 },
  { id:"lasanha_massa_cozida", name:"Massa de lasanha fresca cozida", cat:"carboidrato", kcal:164, p:5.8, c:32.5, g:1.2 },
  { id:"lasanha_massa_crua", name:"Massa de lasanha fresca crua", cat:"carboidrato", kcal:220, p:7, c:45.1, g:1.3 },
  { id:"macarrao_instantaneo", name:"Macarrão instantâneo", cat:"carboidrato", kcal:436, p:8.8, c:62.4, g:17.2 },
  { id:"macarrao_cru", name:"Macarrão de trigo cru", cat:"carboidrato", kcal:371, p:10, c:77.9, g:1.3 },
  { id:"macarrao_ovo_cru", name:"Macarrão de trigo com ovos cru", cat:"carboidrato", kcal:371, p:10.3, c:76.6, g:2 },
  { id:"amido_milho", name:"Amido de milho", cat:"carboidrato", kcal:361, p:0.6, c:87.1, g:0 },
  { id:"batata_baroa_crua", name:"Batata-baroa crua", cat:"carboidrato", kcal:101, p:1, c:24, g:0.2 },
  { id:"batata_doce_crua", name:"Batata-doce crua", cat:"carboidrato", kcal:118, p:1.3, c:28.2, g:0.1 },
  { id:"batata_chips", name:"Batata chips industrializada", cat:"outro", kcal:543, p:5.6, c:51.2, g:36.6 },
  { id:"batata_inglesa_crua", name:"Batata inglesa crua", cat:"carboidrato", kcal:64, p:1.8, c:14.7, g:0 },
  { id:"batata_frita", name:"Batata inglesa frita", cat:"outro", kcal:267, p:5, c:35.6, g:13.1 },
  { id:"batata_soute", name:"Batata inglesa sauté", cat:"carboidrato", kcal:68, p:1.3, c:14.1, g:0.9 },
  { id:"berinjela_cozida", name:"Berinjela cozida", cat:"vegetal", kcal:19, p:0.7, c:4.5, g:0.1 },
  { id:"berinjela_crua", name:"Berinjela crua", cat:"vegetal", kcal:20, p:1.2, c:4.4, g:0.1 },
  { id:"tomate_extrato", name:"Extrato de tomate", cat:"vegetal", kcal:61, p:2.4, c:15, g:0.2 },
  { id:"molho_tomate_industrial", name:"Molho de tomate industrializado", cat:"outro", kcal:38, p:1.4, c:7.7, g:0.9 },
  { id:"pure_tomate", name:"Purê de tomate", cat:"vegetal", kcal:28, p:1.4, c:6.9, g:0 },
  { id:"tomate_salad", name:"Tomate para salada", cat:"vegetal", kcal:21, p:0.8, c:5.1, g:0 },
  { id:"vagem_crua", name:"Vagem crua", cat:"vegetal", kcal:25, p:1.8, c:5.3, g:0.2 },
  { id:"abacaxi_polpa", name:"Abacaxi polpa congelada", cat:"fruta", kcal:31, p:0.5, c:7.8, g:0.1 },
  { id:"abiu", name:"Abiu", cat:"fruta", kcal:62, p:0.8, c:14.9, g:0.7 },
  { id:"acai_xarope", name:"Açaí com xarope de guaraná e glucose", cat:"fruta", kcal:110, p:0.7, c:21.5, g:3.7 },
  { id:"acai_congelado", name:"Açaí polpa congelada", cat:"fruta", kcal:58, p:0.8, c:6.2, g:3.9 },
  { id:"figo_calda", name:"Figo enlatado em calda", cat:"fruta", kcal:184, p:0.6, c:50.3, g:0.2 },
  { id:"fruta_pao", name:"Fruta-pão crua", cat:"fruta", kcal:67, p:1.1, c:17.2, g:0.2 },
  { id:"goiaba_branca", name:"Goiaba branca com casca", cat:"fruta", kcal:52, p:0.9, c:12.4, g:0.5 },
  { id:"goiaba_pasta", name:"Goiaba doce em pasta", cat:"outro", kcal:269, p:0.6, c:74.1, g:0 },
  { id:"goiaba_cascao", name:"Goiaba doce cascão", cat:"outro", kcal:286, p:0.4, c:78.7, g:0.1 },
  { id:"goiaba_vermelha", name:"Goiaba vermelha com casca", cat:"fruta", kcal:54, p:1.1, c:13, g:0.4 },
  { id:"graviola", name:"Graviola crua", cat:"fruta", kcal:62, p:0.8, c:15.8, g:0.2 },
  { id:"graviola_polpa", name:"Graviola polpa congelada", cat:"fruta", kcal:38, p:0.6, c:9.8, g:0.1 },
  { id:"jabuticaba", name:"Jabuticaba", cat:"fruta", kcal:58, p:0.6, c:15.3, g:0.1 },
  { id:"jaca", name:"Jaca crua", cat:"fruta", kcal:88, p:1.4, c:22.5, g:0.3 },
  { id:"jambo", name:"Jambo cru", cat:"fruta", kcal:27, p:0.9, c:6.5, g:0.1 },
  { id:"jamelao", name:"Jamelão cru", cat:"fruta", kcal:41, p:0.5, c:10.6, g:0.1 },
  { id:"nespera", name:"Nêspera crua", cat:"fruta", kcal:43, p:0.3, c:11.5, g:0 },
  { id:"pequi", name:"Pequi cru", cat:"fruta", kcal:205, p:2.3, c:13, g:18 },
  { id:"pera_park", name:"Pera Park crua", cat:"fruta", kcal:61, p:0.2, c:16.1, g:0.2 },
  { id:"pera_williams", name:"Pera Williams crua", cat:"fruta", kcal:53, p:0.6, c:14, g:0.1 },
  { id:"pessego_aurora", name:"Pêssego Aurora cru", cat:"fruta", kcal:36, p:0.8, c:9.3, g:0 },
  { id:"pessego_calda", name:"Pêssego enlatado em calda", cat:"fruta", kcal:63, p:0.7, c:16.9, g:0 },
  { id:"pinha", name:"Pinha crua", cat:"fruta", kcal:88, p:1.5, c:22.4, g:0.3 },
  { id:"pitanga", name:"Pitanga crua", cat:"fruta", kcal:41, p:0.9, c:10.2, g:0.2 },
  { id:"roma", name:"Romã crua", cat:"fruta", kcal:56, p:0.4, c:15.1, g:0 },
  { id:"mexerica_murcote", name:"Mexerica Murcote crua", cat:"fruta", kcal:58, p:0.9, c:14.9, g:0.1 },
  { id:"mexerica_rio", name:"Mexerica Rio crua", cat:"fruta", kcal:37, p:0.7, c:9.3, g:0.1 },
  { id:"oleo_canola", name:"Óleo de canola", cat:"gordura", kcal:884, p:0, c:0, g:100 },
  { id:"oleo_girassol", name:"Óleo de girassol", cat:"gordura", kcal:884, p:0, c:0, g:100 },
  { id:"oleo_milho", name:"Óleo de milho", cat:"gordura", kcal:884, p:0, c:0, g:100 },
  { id:"oleo_soja", name:"Óleo de soja", cat:"gordura", kcal:884, p:0, c:0, g:100 },
  { id:"margarina_com_sal", name:"Margarina com óleo interesterificado com sal", cat:"gordura", kcal:594, p:0, c:0, g:67.2 },
  { id:"margarina_sem_sal", name:"Margarina com óleo interesterificado sem sal", cat:"gordura", kcal:593, p:0, c:0, g:67.1 },
  { id:"abadejo_assado", name:"Abadejo filé assado", cat:"proteina", kcal:112, p:23.5, c:0, g:1.2 },
  { id:"abadejo_cozido", name:"Abadejo filé cozido", cat:"proteina", kcal:91, p:19.3, c:0, g:0.9 },
  { id:"abadejo_cru", name:"Abadejo filé cru", cat:"proteina", kcal:59, p:13.1, c:0, g:0.4 },
  { id:"abadejo_grelhado", name:"Abadejo filé grelhado", cat:"proteina", kcal:130, p:27.6, c:0, g:1.3 },
  { id:"atum_oleo", name:"Atum em conserva em óleo", cat:"proteina", kcal:166, p:26.2, c:0, g:6 },
  { id:"atum_fresco", name:"Atum fresco cru", cat:"proteina", kcal:118, p:25.7, c:0, g:0.9 },
  { id:"bacalhau_salgado", name:"Bacalhau salgado cru", cat:"proteina", kcal:136, p:29, c:0, g:1.3 },
  { id:"bacalhau_refogado", name:"Bacalhau salgado refogado", cat:"proteina", kcal:140, p:24, c:1.2, g:3.6 },
  { id:"sardinha_oleo", name:"Sardinha em conserva em óleo", cat:"proteina", kcal:285, p:15.9, c:0, g:24 },
  { id:"sardinha_frita", name:"Sardinha frita", cat:"proteina", kcal:257, p:33.4, c:0, g:12.7 },
  { id:"sardinha_crua", name:"Sardinha inteira crua", cat:"proteina", kcal:114, p:21.1, c:0, g:2.7 },
  { id:"tucunare", name:"Tucunaré filé cru", cat:"proteina", kcal:88, p:18, c:0, g:1.2 },
  { id:"apresuntado", name:"Apresuntado", cat:"proteina", kcal:129, p:13.5, c:2.9, g:6.7 },
  { id:"caldo_carne_tablete", name:"Caldo de carne em tablete", cat:"outro", kcal:241, p:7.8, c:15.1, g:16.6 },
  { id:"caldo_galinha_tablete", name:"Caldo de galinha em tablete", cat:"outro", kcal:251, p:6.3, c:10.6, g:20.4 },
  { id:"acém_moido_cozido", name:"Acém bovino moído cozido", cat:"proteina", kcal:212, p:26.7, c:0.8, g:10.9 },
  { id:"acém_moido_cru", name:"Acém bovino moído cru", cat:"proteina", kcal:137, p:19.4, c:0.9, g:5.9 },
  { id:"acém_sem_gordura_cozido", name:"Acém bovino sem gordura cozido", cat:"proteina", kcal:215, p:27.3, c:0.8, g:10.9 },
  { id:"acém_sem_gordura_cru", name:"Acém bovino sem gordura cru", cat:"proteina", kcal:144, p:20.8, c:1, g:6.1 },
  { id:"almondega_crua", name:"Almôndega bovina crua", cat:"proteina", kcal:189, p:12.3, c:9.8, g:11.2 },
  { id:"almondega_frita", name:"Almôndega bovina frita", cat:"proteina", kcal:272, p:18.2, c:14.3, g:15.8 },
  { id:"bucho_cozido", name:"Bucho bovino cozido", cat:"proteina", kcal:133, p:21.6, c:0.3, g:4.5 },
  { id:"bucho_cru", name:"Bucho bovino cru", cat:"proteina", kcal:137, p:20.5, c:0.4, g:5.5 },
  { id:"capa_contrafilé_crua", name:"Capa de contrafilé com gordura crua", cat:"proteina", kcal:217, p:19.2, c:0.9, g:15 },
  { id:"capa_contrafilé_grelhada", name:"Capa de contrafilé com gordura grelhada", cat:"proteina", kcal:312, p:30.7, c:1.1, g:20 },
  { id:"file_mignon_cru", name:"Filé mignon sem gordura cru", cat:"proteina", kcal:143, p:21.6, c:1.1, g:5.6 },
  { id:"file_mignon_grelhado", name:"Filé mignon sem gordura grelhado", cat:"proteina", kcal:220, p:32.8, c:1.3, g:8.8 },
  { id:"flanco_cozido", name:"Flanco bovino cozido", cat:"proteina", kcal:196, p:29.4, c:0.9, g:7.8 },
  { id:"flanco_cru", name:"Flanco bovino cru", cat:"proteina", kcal:141, p:20, c:1, g:6.2 },
  { id:"fraldinha_cozida", name:"Fraldinha com gordura cozida", cat:"proteina", kcal:338, p:24.2, c:0.7, g:26 },
  { id:"fraldinha_crua", name:"Fraldinha com gordura crua", cat:"proteina", kcal:221, p:17.6, c:0.9, g:16.1 },
  { id:"lagarto_cozido", name:"Lagarto bovino cozido", cat:"proteina", kcal:222, p:32.9, c:0.9, g:9.1 },
  { id:"lagarto_cru", name:"Lagarto bovino cru", cat:"proteina", kcal:135, p:20.5, c:1.1, g:5.2 },
  { id:"lingua_cozida", name:"Língua bovina cozida", cat:"proteina", kcal:315, p:21.4, c:0.7, g:24.8 },
  { id:"lingua_crua", name:"Língua bovina crua", cat:"proteina", kcal:215, p:17.1, c:0.8, g:15.8 },
  { id:"maminha_crua", name:"Maminha bovina crua", cat:"proteina", kcal:153, p:20.9, c:1, g:7 },
  { id:"maminha_grelhada", name:"Maminha bovina grelhada", cat:"proteina", kcal:153, p:30.7, c:1.4, g:2.4 },
  { id:"coxa_frango_pele_crua", name:"Coxa de frango com pele crua", cat:"proteina", kcal:161, p:17.1, c:0.8, g:9.8 },
  { id:"coxa_frango_sem_pele_cozida", name:"Coxa de frango sem pele cozida", cat:"proteina", kcal:167, p:26.9, c:0.9, g:5.8 },
  { id:"coxa_frango_sem_pele_crua", name:"Coxa de frango sem pele crua", cat:"proteina", kcal:120, p:17.8, c:0.9, g:4.9 },
  { id:"figado_frango_cru", name:"Fígado de frango cru", cat:"proteina", kcal:106, p:17.6, c:1.2, g:3.5 },
  { id:"file_frango_milanesa", name:"Filé de frango à milanesa", cat:"proteina", kcal:221, p:28.5, c:7.5, g:7.8 },
  { id:"frango_inteiro_pele_cru", name:"Frango inteiro com pele cru", cat:"proteina", kcal:226, p:16.4, c:0.7, g:17.3 },
  { id:"frango_inteiro_sem_pele_assado", name:"Frango inteiro sem pele assado", cat:"proteina", kcal:187, p:28, c:1.2, g:7.5 },
  { id:"frango_inteiro_sem_pele_cozido", name:"Frango inteiro sem pele cozido", cat:"proteina", kcal:170, p:25, c:0.9, g:7.1 },
  { id:"frango_peito_pele_assado", name:"Peito de frango com pele assado", cat:"proteina", kcal:212, p:33.4, c:1.5, g:7.6 },
  { id:"frango_peito_pele_cru", name:"Peito de frango com pele cru", cat:"proteina", kcal:149, p:20.8, c:0.9, g:6.7 },
  { id:"frango_peito_sem_pele_cru", name:"Peito de frango sem pele cru", cat:"proteina", kcal:119, p:21.5, c:0.9, g:3 },
  { id:"porco_bisteca_crua", name:"Bisteca suína crua", cat:"proteina", kcal:164, p:21.5, c:1, g:8 },
  { id:"porco_bisteca_frita", name:"Bisteca suína frita", cat:"proteina", kcal:311, p:33.7, c:1.6, g:18.5 },
  { id:"porco_bisteca_grelhada", name:"Bisteca suína grelhada", cat:"proteina", kcal:280, p:28.9, c:1.2, g:17.4 },
  { id:"porco_costela_assada", name:"Costela suína assada", cat:"proteina", kcal:402, p:30.2, c:1.4, g:30.3 },
  { id:"porco_costela_crua", name:"Costela suína crua", cat:"proteina", kcal:256, p:18, c:0.9, g:19.8 },
  { id:"porco_lombo_cru", name:"Lombo suíno cru", cat:"proteina", kcal:176, p:22.6, c:1, g:8.8 },
  { id:"porco_orelha", name:"Orelha suína salgada crua", cat:"proteina", kcal:258, p:18.5, c:2, g:19.9 },
  { id:"porco_pernil_assado", name:"Pernil suíno assado", cat:"proteina", kcal:262, p:32.1, c:1.4, g:13.9 },
  { id:"porco_pernil_cru", name:"Pernil suíno cru", cat:"proteina", kcal:186, p:20.1, c:1, g:11.1 },
  { id:"porco_rabo_salgado", name:"Rabo suíno salgado cru", cat:"proteina", kcal:377, p:15.6, c:3.5, g:34.5 },
  { id:"presunto_com_gordura", name:"Presunto com capa de gordura", cat:"proteina", kcal:128, p:14.4, c:1.4, g:6.8 },
  { id:"toucinho_frito", name:"Toucinho frito", cat:"proteina", kcal:697, p:27.3, c:0.7, g:64.3 },
  { id:"creme_leite", name:"Creme de leite", cat:"laticinio", kcal:221, p:1.5, c:4.5, g:22.5 },
  { id:"iogurte_desnatado", name:"Iogurte natural desnatado", cat:"laticinio", kcal:41, p:3.8, c:5.8, g:0.3 },
  { id:"iogurte_morango", name:"Iogurte sabor morango", cat:"laticinio", kcal:70, p:2.7, c:9.7, g:2.3 },
  { id:"iogurte_pessego", name:"Iogurte sabor pêssego", cat:"laticinio", kcal:68, p:2.5, c:9.4, g:2.3 },
  { id:"leite_condensado", name:"Leite condensado", cat:"laticinio", kcal:313, p:7.7, c:57, g:6.7 },
  { id:"leite_cabra", name:"Leite de cabra", cat:"laticinio", kcal:66, p:3.1, c:5.2, g:3.8 },
  { id:"leite_achocolatado", name:"Leite de vaca achocolatado", cat:"laticinio", kcal:83, p:2.1, c:14.2, g:2.2 },
  { id:"rapadura", name:"Rapadura", cat:"outro", kcal:352, p:1, c:90.8, g:0.1 },
  { id:"marmelada", name:"Marmelada", cat:"outro", kcal:257, p:0.4, c:70.8, g:0.1 },
  { id:"melado", name:"Melado", cat:"outro", kcal:297, p:0, c:76.6, g:0 },
  { id:"quindim", name:"Quindim", cat:"outro", kcal:411, p:4.7, c:46.3, g:24.4 },
  { id:"cafe_po", name:"Café em pó torrado", cat:"outro", kcal:419, p:14.7, c:65.8, g:11.9 },
  { id:"cappuccino_po", name:"Capuccino em pó", cat:"outro", kcal:417, p:11.3, c:73.6, g:8.6 },
  { id:"gelatina_po", name:"Gelatina em pó sabores variados", cat:"outro", kcal:380, p:8.9, c:89.2, g:0 },
  { id:"shoyu", name:"Molho shoyu", cat:"outro", kcal:61, p:3.3, c:11.6, g:0.3 },
  { id:"tapioca_manteiga", name:"Tapioca com manteiga", cat:"carboidrato", kcal:348, p:0.1, c:63.6, g:10.9 },
  { id:"vatapa", name:"Vatapá", cat:"outro", kcal:255, p:6, c:9.7, g:23.2 }
];
