// Banco de alimentos — valores médios por 100g, baseados na Tabela TACO
// (UNICAMP/NEPA) e referências USDA para itens não encontrados na TACO.
// Cada alimento aparece uma única vez (um só valor por tipo de preparo).
// kcal=calorias, p=proteína(g), c=carboidrato(g), g=gordura(g), f=fibra(g)

const CATS = {
  favoritos:  { label: "Mais usados",   icon: "🔥" },
  proteina:   { label: "Proteínas",     icon: "🍗" },
  leguminosa: { label: "Leguminosas",   icon: "🫘" },
  carboidrato:{ label: "Carboidratos",  icon: "🍚" },
  gordura:    { label: "Gorduras",      icon: "🥑" },
  fruta:      { label: "Frutas",        icon: "🍌" },
  vegetal:    { label: "Vegetais",      icon: "🥦" },
  laticinio:  { label: "Laticínios",    icon: "🥛" },
  outro:      { label: "Outros",        icon: "🍯" },
  custom:     { label: "Meus alimentos",icon: "⭐" }
};

const MEALS = {
  cafe:   "Café da manhã",
  almoco: "Almoço",
  lanche: "Lanche",
  jantar: "Jantar"
};

const FOODS = [
  // ---------- PROTEÍNAS ----------
  { id:"frango_peito_grelhado", name:"Peito de frango grelhado", cat:"proteina", kcal:159, p:32, c:0, g:2.5, porc:"1 filé médio ≈ 100 g" },
  { id:"frango_peito_cozido", name:"Peito de frango cozido", cat:"proteina", kcal:163, p:31.5, c:0, g:3.2 },
  { id:"frango_coxa_assada", name:"Coxa de frango assada (sem pele)", cat:"proteina", kcal:179, p:26.2, c:0, g:7.9 },
  { id:"carne_patinho_grelhado", name:"Carne bovina (patinho) grelhada", cat:"proteina", kcal:219, p:35.9, c:0, g:7.3 },
  { id:"carne_moida_refogada", name:"Carne moída (patinho) refogada", cat:"proteina", kcal:212, p:26, c:0, g:11.5 },
  { id:"alcatra_grelhada", name:"Alcatra grelhada", cat:"proteina", kcal:175, p:32, c:0, g:5 },
  { id:"lombo_suino_assado", name:"Lombo suíno assado", cat:"proteina", kcal:210, p:31, c:0, g:9 },
  { id:"bacon_frito", name:"Bacon frito", cat:"proteina", kcal:541, p:37, c:1.4, g:42 },
  { id:"presunto_peru", name:"Peito de peru fatiado", cat:"proteina", kcal:110, p:17, c:2, g:3.5 },
  { id:"atum_lata_natural", name:"Atum em lata ao natural (escorrido)", cat:"proteina", kcal:116, p:25.5, c:0, g:0.8 },
  { id:"sardinha_assada", name:"Sardinha assada", cat:"proteina", kcal:164, p:21, c:0, g:8 },
  { id:"salmao_grelhado", name:"Salmão grelhado", cat:"proteina", kcal:243, p:25, c:0, g:15 },
  { id:"tilapia_grelhada", name:"Tilápia grelhada", cat:"proteina", kcal:96, p:20, c:0, g:1.7 },
  { id:"camarao_cozido", name:"Camarão cozido", cat:"proteina", kcal:99, p:24, c:0.2, g:1 },
  { id:"ovo_cozido", name:"Ovo de galinha cozido", cat:"proteina", kcal:146, p:13.3, c:0.6, g:9.5, porc:"1 ovo médio ≈ 50 g" },
  { id:"ovo_frito", name:"Ovo de galinha frito", cat:"proteina", kcal:240, p:15.6, c:1.2, g:18.6 },
  { id:"clara_ovo_cozida", name:"Clara de ovo cozida", cat:"proteina", kcal:52, p:10.9, c:0.7, g:0.2 },
  { id:"tofu_firme", name:"Tofu firme", cat:"proteina", kcal:76, p:8, c:1.9, g:4.8 },
  { id:"whey_concentrado", name:"Whey protein concentrado (pó)", cat:"proteina", kcal:400, p:80, c:7, g:6, porc:"1 dose ≈ 30 g — varia por marca" },

  // ---------- LEGUMINOSAS ----------
  { id:"feijao_carioca_cozido", name:"Feijão carioca cozido", cat:"leguminosa", kcal:76, p:4.8, c:13.6, g:0.5 },
  { id:"feijao_preto_cozido", name:"Feijão preto cozido", cat:"leguminosa", kcal:77, p:4.5, c:14, g:0.5 },
  { id:"lentilha_cozida", name:"Lentilha cozida", cat:"leguminosa", kcal:93, p:6.3, c:16.3, g:0.5 },
  { id:"grao_de_bico_cozido", name:"Grão de bico cozido", cat:"leguminosa", kcal:164, p:8.9, c:27.4, g:2.6 },
  { id:"ervilha_cozida", name:"Ervilha cozida", cat:"leguminosa", kcal:79, p:5.4, c:14.5, g:0.4 },
  { id:"soja_cozida", name:"Soja cozida", cat:"leguminosa", kcal:173, p:18.2, c:9.9, g:9 },

  // ---------- CARBOIDRATOS ----------
  { id:"arroz_branco_cozido", name:"Arroz branco cozido", cat:"carboidrato", kcal:130, p:2.5, c:28.1, g:0.3 },
  { id:"arroz_integral_cozido", name:"Arroz integral cozido", cat:"carboidrato", kcal:124, p:2.6, c:25.8, g:1 },
  { id:"batata_inglesa_cozida", name:"Batata inglesa cozida", cat:"carboidrato", kcal:52, p:1.2, c:11.9, g:0 },
  { id:"batata_doce_cozida", name:"Batata doce cozida", cat:"carboidrato", kcal:77, p:0.6, c:18.4, g:0.1 },
  { id:"mandioca_cozida", name:"Mandioca cozida", cat:"carboidrato", kcal:125, p:0.6, c:30.1, g:0.3 },
  { id:"macarrao_cozido", name:"Macarrão cozido", cat:"carboidrato", kcal:102, p:3.3, c:19.9, g:1.3 },
  { id:"aveia_flocos", name:"Aveia em flocos (crua)", cat:"carboidrato", kcal:394, p:13.9, c:66.6, g:8.5 },
  { id:"pao_frances", name:"Pão francês", cat:"carboidrato", kcal:300, p:8, c:58.7, g:3.1, porc:"1 unidade ≈ 50 g" },
  { id:"pao_forma_integral", name:"Pão de forma integral", cat:"carboidrato", kcal:253, p:9.6, c:49, g:3.5, porc:"1 fatia ≈ 25 g" },
  { id:"tapioca_goma", name:"Tapioca (goma seca)", cat:"carboidrato", kcal:240, p:0.6, c:58.8, g:0.1 },
  { id:"quinoa_cozida", name:"Quinoa cozida", cat:"carboidrato", kcal:120, p:4.4, c:21.3, g:1.9 },
  { id:"milho_verde_cozido", name:"Milho verde cozido", cat:"carboidrato", kcal:98, p:3.4, c:21, g:1 },
  { id:"cuscuz_milho_cozido", name:"Cuscuz de milho cozido", cat:"carboidrato", kcal:112, p:2.5, c:25, g:0.4 },
  { id:"granola", name:"Granola", cat:"carboidrato", kcal:471, p:10, c:64, g:20 },

  // ---------- GORDURAS ----------
  { id:"azeite_oliva", name:"Azeite de oliva extra virgem", cat:"gordura", kcal:884, p:0, c:0, g:100, porc:"1 colher de sopa ≈ 13 g" },
  { id:"oleo_coco", name:"Óleo de coco", cat:"gordura", kcal:862, p:0, c:0, g:99.1 },
  { id:"manteiga", name:"Manteiga", cat:"gordura", kcal:717, p:0.6, c:0.1, g:81 },
  { id:"castanha_para", name:"Castanha-do-pará", cat:"gordura", kcal:656, p:14.5, c:15, g:66.4 },
  { id:"castanha_caju", name:"Castanha de caju", cat:"gordura", kcal:570, p:18.5, c:29, g:46 },
  { id:"amendoim_torrado", name:"Amendoim torrado", cat:"gordura", kcal:544, p:27.2, c:20, g:43.9 },
  { id:"amendoas", name:"Amêndoas", cat:"gordura", kcal:579, p:21.2, c:21.7, g:49.9 },
  { id:"pasta_amendoim", name:"Pasta de amendoim integral", cat:"gordura", kcal:588, p:25, c:20, g:50 },
  { id:"abacate", name:"Abacate", cat:"gordura", kcal:96, p:1.2, c:6, g:8.4 },

  // ---------- FRUTAS ----------
  { id:"banana_prata", name:"Banana prata", cat:"fruta", kcal:98, p:1.3, c:26, g:0.1, porc:"1 unidade ≈ 70 g" },
  { id:"maca", name:"Maçã", cat:"fruta", kcal:56, p:0.3, c:15.2, g:0, porc:"1 unidade ≈ 130 g" },
  { id:"laranja", name:"Laranja", cat:"fruta", kcal:45, p:1, c:11.5, g:0.1 },
  { id:"morango", name:"Morango", cat:"fruta", kcal:30, p:0.9, c:6.8, g:0.3 },
  { id:"mamao", name:"Mamão", cat:"fruta", kcal:40, p:0.5, c:10.4, g:0.1 },
  { id:"manga", name:"Manga", cat:"fruta", kcal:64, p:0.4, c:16.7, g:0.2 },
  { id:"abacaxi", name:"Abacaxi", cat:"fruta", kcal:48, p:0.9, c:12.3, g:0.1 },
  { id:"melancia", name:"Melancia", cat:"fruta", kcal:33, p:0.9, c:8.1, g:0 },
  { id:"uva", name:"Uva", cat:"fruta", kcal:53, p:0.7, c:13.3, g:0.2 },

  // ---------- VEGETAIS ----------
  { id:"brocolis_cozido", name:"Brócolis cozido", cat:"vegetal", kcal:25, p:3.6, c:4, g:0.3 },
  { id:"couve_crua", name:"Couve manteiga crua (picada)", cat:"vegetal", kcal:27, p:2.9, c:4.3, g:0.5 },
  { id:"alface", name:"Alface", cat:"vegetal", kcal:11, p:1.1, c:1.7, g:0.2 },
  { id:"tomate", name:"Tomate", cat:"vegetal", kcal:15, p:1.1, c:3.1, g:0.2 },
  { id:"cenoura_crua", name:"Cenoura crua", cat:"vegetal", kcal:34, p:1.3, c:7.7, g:0.2 },
  { id:"pepino", name:"Pepino", cat:"vegetal", kcal:10, p:0.9, c:2, g:0.1 },
  { id:"cebola_crua", name:"Cebola crua", cat:"vegetal", kcal:39, p:1.7, c:8.9, g:0.1 },
  { id:"pimentao_vermelho", name:"Pimentão vermelho", cat:"vegetal", kcal:21, p:1, c:4.2, g:0.3 },
  { id:"repolho_cru", name:"Repolho cru", cat:"vegetal", kcal:17, p:1.2, c:3.9, g:0.1 },
  { id:"abobrinha_refogada", name:"Abobrinha refogada", cat:"vegetal", kcal:22, p:1.4, c:3.8, g:0.4 },
  { id:"espinafre_refogado", name:"Espinafre refogado", cat:"vegetal", kcal:22, p:2.4, c:2.5, g:1 },
  { id:"vagem_cozida", name:"Vagem cozida", cat:"vegetal", kcal:21, p:1.8, c:4.3, g:0.1 },
  { id:"chuchu_cozido", name:"Chuchu cozido", cat:"vegetal", kcal:17, p:0.6, c:4, g:0.1 },

  // ---------- LATICÍNIOS ----------
  { id:"leite_integral", name:"Leite integral", cat:"laticinio", kcal:61, p:3, c:4.5, g:3.2 },
  { id:"leite_desnatado", name:"Leite desnatado", cat:"laticinio", kcal:35, p:3.4, c:4.9, g:0.2 },
  { id:"iogurte_natural_integral", name:"Iogurte natural integral", cat:"laticinio", kcal:51, p:4.1, c:1.9, g:3 },
  { id:"iogurte_grego", name:"Iogurte grego natural", cat:"laticinio", kcal:97, p:9, c:4, g:5 },
  { id:"queijo_minas_frescal", name:"Queijo minas frescal", cat:"laticinio", kcal:264, p:17.4, c:3.2, g:20 },
  { id:"queijo_mussarela", name:"Queijo muçarela", cat:"laticinio", kcal:330, p:22.6, c:3, g:25.2 },
  { id:"requeijao_cremoso", name:"Requeijão cremoso", cat:"laticinio", kcal:257, p:9.6, c:3, g:23 },

  // ---------- OUTROS ----------
  { id:"mel", name:"Mel", cat:"outro", kcal:309, p:0.4, c:84, g:0 },
  { id:"acucar_refinado", name:"Açúcar refinado", cat:"outro", kcal:387, p:0, c:99.9, g:0 },
  { id:"chocolate_ao_leite", name:"Chocolate ao leite", cat:"outro", kcal:540, p:7.3, c:58, g:30 },
  { id:"whey_isolado", name:"Whey protein isolado (pó)", cat:"outro", kcal:375, p:85, c:3, g:2, porc:"1 dose ≈ 30 g — varia por marca" },

  { id:"arroz_tipo1_cozido", name:"Arroz tipo 1 cozido", cat:"carboidrato", kcal:128, p:2.5, c:28.1, g:0.2 },
  { id:"arroz_tipo2_cozido", name:"Arroz tipo 2 cozido", cat:"carboidrato", kcal:130, p:2.6, c:28.2, g:0.4 },
  { id:"arroz_tipo1_cru", name:"Arroz tipo 1 cru", cat:"carboidrato", kcal:358, p:7.2, c:78.8, g:0.3 },
  { id:"arroz_integral_cru", name:"Arroz integral cru", cat:"carboidrato", kcal:360, p:7.3, c:77.5, g:1.9 },
  { id:"biscoito_maisena", name:"Biscoito maisena", cat:"outro", kcal:443, p:8.1, c:75.2, g:12 },
  { id:"biscoito_recheado_chocolate", name:"Biscoito recheado com chocolate", cat:"outro", kcal:472, p:6.4, c:70.5, g:19.6 },
  { id:"biscoito_recheado_morango", name:"Biscoito recheado com morango", cat:"outro", kcal:471, p:5.7, c:71, g:19.6 },
  { id:"biscoito_wafer_chocolate", name:"Biscoito wafer recheado de chocolate", cat:"outro", kcal:502, p:5.6, c:67.5, g:24.7 },
  { id:"biscoito_wafer_morango", name:"Biscoito wafer recheado de morango", cat:"outro", kcal:513, p:4.5, c:67.4, g:26.4 },
  { id:"cream_cracker", name:"Biscoito salgado cream cracker", cat:"outro", kcal:432, p:10.1, c:68.7, g:14.4 },
  { id:"bolo_mistura", name:"Bolo, mistura para", cat:"outro", kcal:419, p:6.2, c:84.7, g:6.1 },
  { id:"bolo_aipim", name:"Bolo de aipim", cat:"outro", kcal:324, p:4.4, c:47.9, g:12.7 },
  { id:"bolo_chocolate", name:"Bolo de chocolate", cat:"outro", kcal:410, p:6.2, c:54.7, g:18.5 },
  { id:"farinha_centeio_integral", name:"Farinha de centeio integral", cat:"carboidrato", kcal:336, p:12.5, c:73.3, g:1.8 },
  { id:"farinha_milho_amarela", name:"Farinha de milho amarela", cat:"carboidrato", kcal:351, p:7.2, c:79.1, g:1.5 },
  { id:"farinha_rosca", name:"Farinha de rosca", cat:"carboidrato", kcal:371, p:11.4, c:75.8, g:1.5 },
  { id:"farinha_trigo", name:"Farinha de trigo", cat:"carboidrato", kcal:360, p:9.8, c:75.1, g:1.4 },
  { id:"farinha_lactea", name:"Farinha láctea de cereais", cat:"outro", kcal:415, p:11.9, c:77.8, g:5.8 },
  { id:"lasanha_massa_cozida", name:"Massa de lasanha fresca cozida", cat:"carboidrato", kcal:164, p:5.8, c:32.5, g:1.2 },
  { id:"lasanha_massa_crua", name:"Massa de lasanha fresca crua", cat:"carboidrato", kcal:220, p:7, c:45.1, g:1.3 },
  { id:"macarrao_instantaneo", name:"Macarrão instantâneo", cat:"carboidrato", kcal:436, p:8.8, c:62.4, g:17.2 },
  { id:"macarrao_cru", name:"Macarrão de trigo cru", cat:"carboidrato", kcal:371, p:10, c:77.9, g:1.3 },
  { id:"macarrao_ovo_cru", name:"Macarrão de trigo com ovos cru", cat:"carboidrato", kcal:371, p:10.3, c:76.6, g:2 },
  { id:"amido_milho", name:"Amido de milho", cat:"carboidrato", kcal:361, p:0.6, c:87.1, g:0 },
  { id:"batata_baroa_crua", name:"Batata-baroa crua", cat:"carboidrato", kcal:101, p:1, c:24, g:0.2 },
  { id:"batata_doce_crua", name:"Batata-doce crua", cat:"carboidrato", kcal:118, p:1.3, c:28.2, g:0.1 },
  { id:"batata_chips", name:"Batata chips industrializada", cat:"outro", kcal:543, p:5.6, c:51.2, g:36.6 },
  { id:"batata_inglesa_crua", name:"Batata inglesa crua", cat:"carboidrato", kcal:64, p:1.8, c:14.7, g:0 },
  { id:"batata_frita", name:"Batata inglesa frita", cat:"outro", kcal:267, p:5, c:35.6, g:13.1 },
  { id:"batata_soute", name:"Batata inglesa sauté", cat:"carboidrato", kcal:68, p:1.3, c:14.1, g:0.9 },
  { id:"berinjela_cozida", name:"Berinjela cozida", cat:"vegetal", kcal:19, p:0.7, c:4.5, g:0.1 },
  { id:"berinjela_crua", name:"Berinjela crua", cat:"vegetal", kcal:20, p:1.2, c:4.4, g:0.1 },
  { id:"tomate_extrato", name:"Extrato de tomate", cat:"vegetal", kcal:61, p:2.4, c:15, g:0.2 },
  { id:"molho_tomate_industrial", name:"Molho de tomate industrializado", cat:"outro", kcal:38, p:1.4, c:7.7, g:0.9 },
  { id:"pure_tomate", name:"Purê de tomate", cat:"vegetal", kcal:28, p:1.4, c:6.9, g:0 },
  { id:"tomate_salad", name:"Tomate para salada", cat:"vegetal", kcal:21, p:0.8, c:5.1, g:0 },
  { id:"vagem_crua", name:"Vagem crua", cat:"vegetal", kcal:25, p:1.8, c:5.3, g:0.2 },
  { id:"abacaxi_polpa", name:"Abacaxi polpa congelada", cat:"fruta", kcal:31, p:0.5, c:7.8, g:0.1 },
  { id:"abiu", name:"Abiu", cat:"fruta", kcal:62, p:0.8, c:14.9, g:0.7 },
  { id:"acai_xarope", name:"Açaí com xarope de guaraná e glucose", cat:"fruta", kcal:110, p:0.7, c:21.5, g:3.7 },
  { id:"acai_congelado", name:"Açaí polpa congelada", cat:"fruta", kcal:58, p:0.8, c:6.2, g:3.9 },
  { id:"figo_calda", name:"Figo enlatado em calda", cat:"fruta", kcal:184, p:0.6, c:50.3, g:0.2 },
  { id:"fruta_pao", name:"Fruta-pão crua", cat:"fruta", kcal:67, p:1.1, c:17.2, g:0.2 },
  { id:"goiaba_branca", name:"Goiaba branca com casca", cat:"fruta", kcal:52, p:0.9, c:12.4, g:0.5 },
  { id:"goiaba_pasta", name:"Goiaba doce em pasta", cat:"outro", kcal:269, p:0.6, c:74.1, g:0 },
  { id:"goiaba_cascao", name:"Goiaba doce cascão", cat:"outro", kcal:286, p:0.4, c:78.7, g:0.1 },
  { id:"goiaba_vermelha", name:"Goiaba vermelha com casca", cat:"fruta", kcal:54, p:1.1, c:13, g:0.4 },
  { id:"graviola", name:"Graviola crua", cat:"fruta", kcal:62, p:0.8, c:15.8, g:0.2 },
  { id:"graviola_polpa", name:"Graviola polpa congelada", cat:"fruta", kcal:38, p:0.6, c:9.8, g:0.1 },
  { id:"jabuticaba", name:"Jabuticaba", cat:"fruta", kcal:58, p:0.6, c:15.3, g:0.1 },
  { id:"jaca", name:"Jaca crua", cat:"fruta", kcal:88, p:1.4, c:22.5, g:0.3 },
  { id:"jambo", name:"Jambo cru", cat:"fruta", kcal:27, p:0.9, c:6.5, g:0.1 },
  { id:"jamelao", name:"Jamelão cru", cat:"fruta", kcal:41, p:0.5, c:10.6, g:0.1 },
  { id:"nespera", name:"Nêspera crua", cat:"fruta", kcal:43, p:0.3, c:11.5, g:0 },
  { id:"pequi", name:"Pequi cru", cat:"fruta", kcal:205, p:2.3, c:13, g:18 },
  { id:"pera_park", name:"Pera Park crua", cat:"fruta", kcal:61, p:0.2, c:16.1, g:0.2 },
  { id:"pera_williams", name:"Pera Williams crua", cat:"fruta", kcal:53, p:0.6, c:14, g:0.1 },
  { id:"pessego_aurora", name:"Pêssego Aurora cru", cat:"fruta", kcal:36, p:0.8, c:9.3, g:0 },
  { id:"pessego_calda", name:"Pêssego enlatado em calda", cat:"fruta", kcal:63, p:0.7, c:16.9, g:0 },
  { id:"pinha", name:"Pinha crua", cat:"fruta", kcal:88, p:1.5, c:22.4, g:0.3 },
  { id:"pitanga", name:"Pitanga crua", cat:"fruta", kcal:41, p:0.9, c:10.2, g:0.2 },
  { id:"roma", name:"Romã crua", cat:"fruta", kcal:56, p:0.4, c:15.1, g:0 },
  { id:"mexerica_murcote", name:"Mexerica Murcote crua", cat:"fruta", kcal:58, p:0.9, c:14.9, g:0.1 },
  { id:"mexerica_rio", name:"Mexerica Rio crua", cat:"fruta", kcal:37, p:0.7, c:9.3, g:0.1 },
  { id:"oleo_canola", name:"Óleo de canola", cat:"gordura", kcal:884, p:0, c:0, g:100 },
  { id:"oleo_girassol", name:"Óleo de girassol", cat:"gordura", kcal:884, p:0, c:0, g:100 },
  { id:"oleo_milho", name:"Óleo de milho", cat:"gordura", kcal:884, p:0, c:0, g:100 },
  { id:"oleo_soja", name:"Óleo de soja", cat:"gordura", kcal:884, p:0, c:0, g:100 },
  { id:"margarina_com_sal", name:"Margarina com óleo interesterificado com sal", cat:"gordura", kcal:594, p:0, c:0, g:67.2 },
  { id:"margarina_sem_sal", name:"Margarina com óleo interesterificado sem sal", cat:"gordura", kcal:593, p:0, c:0, g:67.1 },
  { id:"abadejo_assado", name:"Abadejo filé assado", cat:"proteina", kcal:112, p:23.5, c:0, g:1.2 },
  { id:"abadejo_cozido", name:"Abadejo filé cozido", cat:"proteina", kcal:91, p:19.3, c:0, g:0.9 },
  { id:"abadejo_cru", name:"Abadejo filé cru", cat:"proteina", kcal:59, p:13.1, c:0, g:0.4 },
  { id:"abadejo_grelhado", name:"Abadejo filé grelhado", cat:"proteina", kcal:130, p:27.6, c:0, g:1.3 },
  { id:"atum_oleo", name:"Atum em conserva em óleo", cat:"proteina", kcal:166, p:26.2, c:0, g:6 },
  { id:"atum_fresco", name:"Atum fresco cru", cat:"proteina", kcal:118, p:25.7, c:0, g:0.9 },
  { id:"bacalhau_salgado", name:"Bacalhau salgado cru", cat:"proteina", kcal:136, p:29, c:0, g:1.3 },
  { id:"bacalhau_refogado", name:"Bacalhau salgado refogado", cat:"proteina", kcal:140, p:24, c:1.2, g:3.6 },
  { id:"sardinha_oleo", name:"Sardinha em conserva em óleo", cat:"proteina", kcal:285, p:15.9, c:0, g:24 },
  { id:"sardinha_frita", name:"Sardinha frita", cat:"proteina", kcal:257, p:33.4, c:0, g:12.7 },
  { id:"sardinha_crua", name:"Sardinha inteira crua", cat:"proteina", kcal:114, p:21.1, c:0, g:2.7 },
  { id:"tucunare", name:"Tucunaré filé cru", cat:"proteina", kcal:88, p:18, c:0, g:1.2 },
  { id:"apresuntado", name:"Apresuntado", cat:"proteina", kcal:129, p:13.5, c:2.9, g:6.7 },
  { id:"caldo_carne_tablete", name:"Caldo de carne em tablete", cat:"outro", kcal:241, p:7.8, c:15.1, g:16.6 },
  { id:"caldo_galinha_tablete", name:"Caldo de galinha em tablete", cat:"outro", kcal:251, p:6.3, c:10.6, g:20.4 },
  { id:"acém_moido_cozido", name:"Acém bovino moído cozido", cat:"proteina", kcal:212, p:26.7, c:0.8, g:10.9 },
  { id:"acém_moido_cru", name:"Acém bovino moído cru", cat:"proteina", kcal:137, p:19.4, c:0.9, g:5.9 },
  { id:"acém_sem_gordura_cozido", name:"Acém bovino sem gordura cozido", cat:"proteina", kcal:215, p:27.3, c:0.8, g:10.9 },
  { id:"acém_sem_gordura_cru", name:"Acém bovino sem gordura cru", cat:"proteina", kcal:144, p:20.8, c:1, g:6.1 },
  { id:"almondega_crua", name:"Almôndega bovina crua", cat:"proteina", kcal:189, p:12.3, c:9.8, g:11.2 },
  { id:"almondega_frita", name:"Almôndega bovina frita", cat:"proteina", kcal:272, p:18.2, c:14.3, g:15.8 },
  { id:"bucho_cozido", name:"Bucho bovino cozido", cat:"proteina", kcal:133, p:21.6, c:0.3, g:4.5 },
  { id:"bucho_cru", name:"Bucho bovino cru", cat:"proteina", kcal:137, p:20.5, c:0.4, g:5.5 },
  { id:"capa_contrafilé_crua", name:"Capa de contrafilé com gordura crua", cat:"proteina", kcal:217, p:19.2, c:0.9, g:15 },
  { id:"capa_contrafilé_grelhada", name:"Capa de contrafilé com gordura grelhada", cat:"proteina", kcal:312, p:30.7, c:1.1, g:20 },
  { id:"file_mignon_cru", name:"Filé mignon sem gordura cru", cat:"proteina", kcal:143, p:21.6, c:1.1, g:5.6 },
  { id:"file_mignon_grelhado", name:"Filé mignon sem gordura grelhado", cat:"proteina", kcal:220, p:32.8, c:1.3, g:8.8 },
  { id:"flanco_cozido", name:"Flanco bovino cozido", cat:"proteina", kcal:196, p:29.4, c:0.9, g:7.8 },
  { id:"flanco_cru", name:"Flanco bovino cru", cat:"proteina", kcal:141, p:20, c:1, g:6.2 },
  { id:"fraldinha_cozida", name:"Fraldinha com gordura cozida", cat:"proteina", kcal:338, p:24.2, c:0.7, g:26 },
  { id:"fraldinha_crua", name:"Fraldinha com gordura crua", cat:"proteina", kcal:221, p:17.6, c:0.9, g:16.1 },
  { id:"lagarto_cozido", name:"Lagarto bovino cozido", cat:"proteina", kcal:222, p:32.9, c:0.9, g:9.1 },
  { id:"lagarto_cru", name:"Lagarto bovino cru", cat:"proteina", kcal:135, p:20.5, c:1.1, g:5.2 },
  { id:"lingua_cozida", name:"Língua bovina cozida", cat:"proteina", kcal:315, p:21.4, c:0.7, g:24.8 },
  { id:"lingua_crua", name:"Língua bovina crua", cat:"proteina", kcal:215, p:17.1, c:0.8, g:15.8 },
  { id:"maminha_crua", name:"Maminha bovina crua", cat:"proteina", kcal:153, p:20.9, c:1, g:7 },
  { id:"maminha_grelhada", name:"Maminha bovina grelhada", cat:"proteina", kcal:153, p:30.7, c:1.4, g:2.4 },
  { id:"coxa_frango_pele_crua", name:"Coxa de frango com pele crua", cat:"proteina", kcal:161, p:17.1, c:0.8, g:9.8 },
  { id:"coxa_frango_sem_pele_cozida", name:"Coxa de frango sem pele cozida", cat:"proteina", kcal:167, p:26.9, c:0.9, g:5.8 },
  { id:"coxa_frango_sem_pele_crua", name:"Coxa de frango sem pele crua", cat:"proteina", kcal:120, p:17.8, c:0.9, g:4.9 },
  { id:"figado_frango_cru", name:"Fígado de frango cru", cat:"proteina", kcal:106, p:17.6, c:1.2, g:3.5 },
  { id:"file_frango_milanesa", name:"Filé de frango à milanesa", cat:"proteina", kcal:221, p:28.5, c:7.5, g:7.8 },
  { id:"frango_inteiro_pele_cru", name:"Frango inteiro com pele cru", cat:"proteina", kcal:226, p:16.4, c:0.7, g:17.3 },
  { id:"frango_inteiro_sem_pele_assado", name:"Frango inteiro sem pele assado", cat:"proteina", kcal:187, p:28, c:1.2, g:7.5 },
  { id:"frango_inteiro_sem_pele_cozido", name:"Frango inteiro sem pele cozido", cat:"proteina", kcal:170, p:25, c:0.9, g:7.1 },
  { id:"frango_peito_pele_assado", name:"Peito de frango com pele assado", cat:"proteina", kcal:212, p:33.4, c:1.5, g:7.6 },
  { id:"frango_peito_pele_cru", name:"Peito de frango com pele cru", cat:"proteina", kcal:149, p:20.8, c:0.9, g:6.7 },
  { id:"frango_peito_sem_pele_cru", name:"Peito de frango sem pele cru", cat:"proteina", kcal:119, p:21.5, c:0.9, g:3 },
  { id:"porco_bisteca_crua", name:"Bisteca suína crua", cat:"proteina", kcal:164, p:21.5, c:1, g:8 },
  { id:"porco_bisteca_frita", name:"Bisteca suína frita", cat:"proteina", kcal:311, p:33.7, c:1.6, g:18.5 },
  { id:"porco_bisteca_grelhada", name:"Bisteca suína grelhada", cat:"proteina", kcal:280, p:28.9, c:1.2, g:17.4 },
  { id:"porco_costela_assada", name:"Costela suína assada", cat:"proteina", kcal:402, p:30.2, c:1.4, g:30.3 },
  { id:"porco_costela_crua", name:"Costela suína crua", cat:"proteina", kcal:256, p:18, c:0.9, g:19.8 },
  { id:"porco_lombo_cru", name:"Lombo suíno cru", cat:"proteina", kcal:176, p:22.6, c:1, g:8.8 },
  { id:"porco_orelha", name:"Orelha suína salgada crua", cat:"proteina", kcal:258, p:18.5, c:2, g:19.9 },
  { id:"porco_pernil_assado", name:"Pernil suíno assado", cat:"proteina", kcal:262, p:32.1, c:1.4, g:13.9 },
  { id:"porco_pernil_cru", name:"Pernil suíno cru", cat:"proteina", kcal:186, p:20.1, c:1, g:11.1 },
  { id:"porco_rabo_salgado", name:"Rabo suíno salgado cru", cat:"proteina", kcal:377, p:15.6, c:3.5, g:34.5 },
  { id:"presunto_com_gordura", name:"Presunto com capa de gordura", cat:"proteina", kcal:128, p:14.4, c:1.4, g:6.8 },
  { id:"toucinho_frito", name:"Toucinho frito", cat:"proteina", kcal:697, p:27.3, c:0.7, g:64.3 },
  { id:"creme_leite", name:"Creme de leite", cat:"laticinio", kcal:221, p:1.5, c:4.5, g:22.5 },
  { id:"iogurte_desnatado", name:"Iogurte natural desnatado", cat:"laticinio", kcal:41, p:3.8, c:5.8, g:0.3 },
  { id:"iogurte_morango", name:"Iogurte sabor morango", cat:"laticinio", kcal:70, p:2.7, c:9.7, g:2.3 },
  { id:"iogurte_pessego", name:"Iogurte sabor pêssego", cat:"laticinio", kcal:68, p:2.5, c:9.4, g:2.3 },
  { id:"leite_condensado", name:"Leite condensado", cat:"laticinio", kcal:313, p:7.7, c:57, g:6.7 },
  { id:"leite_cabra", name:"Leite de cabra", cat:"laticinio", kcal:66, p:3.1, c:5.2, g:3.8 },
  { id:"leite_achocolatado", name:"Leite de vaca achocolatado", cat:"laticinio", kcal:83, p:2.1, c:14.2, g:2.2 },
  { id:"rapadura", name:"Rapadura", cat:"outro", kcal:352, p:1, c:90.8, g:0.1 },
  { id:"marmelada", name:"Marmelada", cat:"outro", kcal:257, p:0.4, c:70.8, g:0.1 },
  { id:"melado", name:"Melado", cat:"outro", kcal:297, p:0, c:76.6, g:0 },
  { id:"quindim", name:"Quindim", cat:"outro", kcal:411, p:4.7, c:46.3, g:24.4 },
  { id:"cafe_po", name:"Café em pó torrado", cat:"outro", kcal:419, p:14.7, c:65.8, g:11.9 },
  { id:"cappuccino_po", name:"Capuccino em pó", cat:"outro", kcal:417, p:11.3, c:73.6, g:8.6 },
  { id:"gelatina_po", name:"Gelatina em pó sabores variados", cat:"outro", kcal:380, p:8.9, c:89.2, g:0 },
  { id:"shoyu", name:"Molho shoyu", cat:"outro", kcal:61, p:3.3, c:11.6, g:0.3 },
  { id:"tapioca_manteiga", name:"Tapioca com manteiga", cat:"carboidrato", kcal:348, p:0.1, c:63.6, g:10.9 },
  { id:"vatapa", name:"Vatapá", cat:"outro", kcal:255, p:6, c:9.7, g:23.2 },

  // ================= +100 ALIMENTOS (2ª leva) =================
  // ---------- PROTEÍNAS ----------
  { id:"frango_sobrecoxa_assada", name:"Frango sobrecoxa sem pele assada", cat:"proteina", kcal:233, p:29.2, c:0, g:12 },
  { id:"asa_frango_assada", name:"Asa de frango assada", cat:"proteina", kcal:203, p:30.5, c:0, g:8.1 },
  { id:"ovo_codorna_cozido", name:"Ovo de codorna cozido", cat:"proteina", kcal:158, p:13.1, c:0.4, g:11.1, porc:"1 unidade ≈ 9 g" },
  { id:"merluza_grelhada", name:"Merluza grelhada", cat:"proteina", kcal:90, p:18, c:0, g:1.5 },
  { id:"pescada_cozida", name:"Pescada cozida", cat:"proteina", kcal:84, p:17.6, c:0, g:1 },
  { id:"polvo_cozido", name:"Polvo cozido", cat:"proteina", kcal:92, p:18, c:2.2, g:1 },
  { id:"lula_grelhada", name:"Lula grelhada", cat:"proteina", kcal:92, p:15.6, c:3.1, g:1.4 },
  { id:"camarao_frito", name:"Camarão frito (empanado)", cat:"proteina", kcal:242, p:17, c:13, g:14, f:0.5 },
  { id:"carne_seca_cozida", name:"Carne seca cozida (dessalgada)", cat:"proteina", kcal:172, p:28.6, c:0, g:5.5 },
  { id:"mortadela", name:"Mortadela", cat:"proteina", kcal:269, p:12, c:3, g:23 },
  { id:"salsicha", name:"Salsicha (hot dog)", cat:"proteina", kcal:257, p:12, c:3, g:22 },
  { id:"proteina_soja_texturizada", name:"Proteína de soja texturizada (seca)", cat:"proteina", kcal:327, p:51.1, c:32.9, g:3.3, f:17.5 },
  { id:"figado_bovino_grelhado", name:"Fígado bovino grelhado", cat:"proteina", kcal:175, p:26, c:4, g:5.5 },
  { id:"linguica_toscana_grelhada", name:"Linguiça toscana grelhada", cat:"proteina", kcal:320, p:17, c:1.5, g:27 },
  { id:"file_tilapia_empanado", name:"Filé de tilápia empanado frito", cat:"proteina", kcal:200, p:18, c:10, g:10, f:0.5 },
  { id:"atum_grelhado_fresco", name:"Atum fresco grelhado", cat:"proteina", kcal:130, p:28, c:0, g:1.5 },

  // ---------- LEGUMINOSAS ----------
  { id:"feijao_branco_cozido", name:"Feijão branco cozido", cat:"leguminosa", kcal:91, p:6.5, c:16.5, g:0.5, f:6.4 },
  { id:"feijao_fradinho_cozido", name:"Feijão fradinho cozido", cat:"leguminosa", kcal:76, p:4.7, c:13.4, g:0.5, f:6.5 },
  { id:"ervilha_seca_cozida", name:"Ervilha seca cozida", cat:"leguminosa", kcal:118, p:7.9, c:20.9, g:0.5, f:5 },
  { id:"edamame_cozido", name:"Edamame cozido", cat:"leguminosa", kcal:121, p:11, c:10, g:5, f:5 },
  { id:"grao_bico_torrado", name:"Grão de bico torrado (snack)", cat:"leguminosa", kcal:396, p:20.5, c:61, g:6, f:10.7 },
  { id:"feijao_azuki_cozido", name:"Feijão azuki cozido", cat:"leguminosa", kcal:127, p:7.5, c:24.8, g:0.1, f:7.3 },

  // ---------- CARBOIDRATOS ----------
  { id:"pao_de_queijo_assado", name:"Pão de queijo assado", cat:"carboidrato", kcal:363, p:5.1, c:34.2, g:24.6, porc:"1 unidade média ≈ 30 g" },
  { id:"bolo_fuba", name:"Bolo de fubá", cat:"carboidrato", kcal:310, p:5.4, c:45, g:12 },
  { id:"broa_de_milho", name:"Broa de milho", cat:"carboidrato", kcal:290, p:5, c:55, g:6 },
  { id:"inhame_cozido", name:"Inhame cozido", cat:"carboidrato", kcal:118, p:2.1, c:23.2, g:0.2, f:3.4 },
  { id:"batata_doce_assada", name:"Batata doce assada", cat:"carboidrato", kcal:90, p:1.6, c:20.7, g:0.1, f:2.5 },
  { id:"arroz_parboilizado_cozido", name:"Arroz parboilizado cozido", cat:"carboidrato", kcal:123, p:2.6, c:26.2, g:0.7, f:1.8 },
  { id:"pao_sirio", name:"Pão sírio", cat:"carboidrato", kcal:275, p:9, c:56, g:1.5, f:2.3 },
  { id:"bisnaguinha", name:"Bisnaguinha (pãozinho doce)", cat:"carboidrato", kcal:300, p:8, c:58, g:3.5, porc:"1 unidade ≈ 20 g" },
  { id:"torrada", name:"Torrada", cat:"carboidrato", kcal:395, p:11, c:74, g:5, f:4 },
  { id:"panqueca_massa", name:"Panqueca (massa simples)", cat:"carboidrato", kcal:200, p:7, c:26, g:7 },
  { id:"farofa_pronta", name:"Farofa pronta (temperada)", cat:"carboidrato", kcal:365, p:2, c:80, g:3, f:6.5 },
  { id:"pipoca_sem_oleo", name:"Pipoca (estourada, sem óleo)", cat:"carboidrato", kcal:375, p:11, c:74, g:4.5, f:14.5 },
  { id:"batata_baroa_cozida", name:"Batata-baroa cozida", cat:"carboidrato", kcal:80, p:1.5, c:18.6, g:0.3, f:1.5 },
  { id:"aveia_cozida_mingau", name:"Mingau de aveia (aveia cozida)", cat:"carboidrato", kcal:71, p:2.5, c:12, g:1.5, f:1.7 },
  { id:"macarrao_integral_cozido", name:"Macarrão integral cozido", cat:"carboidrato", kcal:124, p:5, c:25, g:1, f:3.5 },
  { id:"nhoque_batata", name:"Nhoque de batata cozido", cat:"carboidrato", kcal:130, p:3.3, c:26.8, g:1.3 },
  { id:"polenta_cozida", name:"Polenta cozida (mole)", cat:"carboidrato", kcal:70, p:1.6, c:14.8, g:0.6 },
  { id:"cuscuz_marroquino_cozido", name:"Cuscuz marroquino cozido", cat:"carboidrato", kcal:112, p:3.8, c:23.2, g:0.2, f:1.4 },

  // ---------- GORDURAS ----------
  { id:"azeitona_preta", name:"Azeitona preta em conserva", cat:"gordura", kcal:115, p:0.8, c:6, g:11, f:3 },
  { id:"azeitona_verde", name:"Azeitona verde em conserva", cat:"gordura", kcal:145, p:1, c:3.8, g:15, f:3.3 },
  { id:"nozes", name:"Nozes", cat:"gordura", kcal:654, p:15.2, c:13.7, g:65.2, f:6.7 },
  { id:"pistache", name:"Pistache", cat:"gordura", kcal:560, p:20.3, c:27.5, g:45.3, f:10.3 },
  { id:"semente_chia", name:"Semente de chia", cat:"gordura", kcal:486, p:16.5, c:42.1, g:30.7, f:34.4 },
  { id:"semente_linhaca", name:"Semente de linhaça", cat:"gordura", kcal:534, p:18.3, c:28.9, g:42.2, f:27.3 },
  { id:"macadamia", name:"Castanha macadâmia", cat:"gordura", kcal:718, p:7.9, c:13.8, g:75.8, f:8.6 },
  { id:"avela", name:"Avelã", cat:"gordura", kcal:628, p:15, c:16.7, g:60.8, f:9.7 },
  { id:"semente_girassol", name:"Semente de girassol torrada", cat:"gordura", kcal:584, p:20.8, c:20, g:49.6, f:8.6 },
  { id:"oleo_amendoim", name:"Óleo de amendoim", cat:"gordura", kcal:884, p:0, c:0, g:100 },

  // ---------- FRUTAS ----------
  { id:"kiwi", name:"Kiwi", cat:"fruta", kcal:61, p:1.1, c:14.7, g:0.5, f:3 },
  { id:"maracuja_polpa", name:"Maracujá polpa", cat:"fruta", kcal:68, p:2.2, c:13.3, g:0.7 },
  { id:"ameixa", name:"Ameixa fresca", cat:"fruta", kcal:46, p:0.7, c:11.4, g:0.3, f:1.4 },
  { id:"ameixa_seca", name:"Ameixa seca", cat:"fruta", kcal:240, p:2.2, c:63.9, g:0.4, f:7.1 },
  { id:"coco_fresco", name:"Coco fresco (polpa)", cat:"fruta", kcal:354, p:3.3, c:15.2, g:33.5, f:9 },
  { id:"agua_de_coco", name:"Água de coco", cat:"fruta", kcal:22, p:0.7, c:5.3, g:0.2, f:1.1 },
  { id:"caju_fruto", name:"Caju (fruto)", cat:"fruta", kcal:43, p:1, c:10.2, g:0.3, f:1.5 },
  { id:"cupuacu_polpa", name:"Cupuaçu polpa", cat:"fruta", kcal:47, p:1.1, c:11.2, g:0.5, f:1 },
  { id:"amora", name:"Amora", cat:"fruta", kcal:43, p:1.4, c:9.6, g:0.5, f:5.3 },
  { id:"framboesa", name:"Framboesa", cat:"fruta", kcal:52, p:1.2, c:11.9, g:0.7, f:6.5 },
  { id:"mirtilo", name:"Mirtilo", cat:"fruta", kcal:57, p:0.7, c:14.5, g:0.3, f:2.4 },
  { id:"carambola", name:"Carambola", cat:"fruta", kcal:31, p:1, c:6.7, g:0.3, f:2.8 },
  { id:"caqui", name:"Caqui", cat:"fruta", kcal:70, p:0.6, c:18.6, g:0.2, f:3.6 },
  { id:"tamarindo_polpa", name:"Tamarindo polpa", cat:"fruta", kcal:239, p:2.8, c:62.5, g:0.6, f:5.1 },
  { id:"damasco_seco", name:"Damasco seco", cat:"fruta", kcal:241, p:3.4, c:62.6, g:0.5, f:7.3 },
  { id:"limao_taiti", name:"Limão taiti (polpa)", cat:"fruta", kcal:22, p:0.7, c:7, g:0.2, f:2 },

  // ---------- VEGETAIS ----------
  { id:"abobora_cozida", name:"Abóbora cozida", cat:"vegetal", kcal:40, p:1.1, c:10, g:0.1, f:2 },
  { id:"beterraba_cozida", name:"Beterraba cozida", cat:"vegetal", kcal:44, p:1.7, c:10, g:0.2, f:2.9 },
  { id:"rucula", name:"Rúcula", cat:"vegetal", kcal:25, p:2.6, c:3.7, g:0.7, f:1.6 },
  { id:"agriao", name:"Agrião", cat:"vegetal", kcal:22, p:2.6, c:3, g:0.5, f:1.5 },
  { id:"cogumelo_paris", name:"Cogumelo Paris (champignon)", cat:"vegetal", kcal:22, p:3.1, c:3.3, g:0.3, f:1 },
  { id:"cogumelo_shitake", name:"Cogumelo shitake", cat:"vegetal", kcal:34, p:2.2, c:6.8, g:0.5, f:2.5 },
  { id:"quiabo_cozido", name:"Quiabo cozido", cat:"vegetal", kcal:33, p:2, c:7.5, g:0.2, f:3.2 },
  { id:"nabo_cozido", name:"Nabo cozido", cat:"vegetal", kcal:22, p:0.7, c:5.1, g:0.1, f:1.8 },
  { id:"rabanete", name:"Rabanete", cat:"vegetal", kcal:16, p:0.7, c:3.4, g:0.1, f:1.6 },
  { id:"aspargo_cozido", name:"Aspargo cozido", cat:"vegetal", kcal:22, p:2.4, c:4.1, g:0.2, f:2 },
  { id:"palmito_conserva", name:"Palmito em conserva", cat:"vegetal", kcal:26, p:2.2, c:4.5, g:0.4, f:3.3 },
  { id:"jilo_cozido", name:"Jiló cozido", cat:"vegetal", kcal:31, p:1.6, c:6.3, g:0.3, f:2.5 },

  // ---------- LATICÍNIOS ----------
  { id:"queijo_cottage", name:"Queijo cottage", cat:"laticinio", kcal:98, p:11, c:3.4, g:4.3 },
  { id:"ricota", name:"Ricota", cat:"laticinio", kcal:146, p:11.3, c:3.8, g:10.3 },
  { id:"queijo_prato", name:"Queijo prato", cat:"laticinio", kcal:360, p:23, c:1.9, g:29 },
  { id:"queijo_parmesao", name:"Queijo parmesão ralado", cat:"laticinio", kcal:431, p:38, c:3.2, g:29 },
  { id:"queijo_provolone", name:"Queijo provolone", cat:"laticinio", kcal:351, p:25.6, c:2.1, g:26.6 },
  { id:"leite_po_integral", name:"Leite em pó integral", cat:"laticinio", kcal:496, p:25.4, c:38.4, g:26.9 },
  { id:"bebida_lactea_morango", name:"Bebida láctea sabor morango", cat:"laticinio", kcal:61, p:1.5, c:11.8, g:1 },
  { id:"kefir_natural", name:"Kefir natural", cat:"laticinio", kcal:55, p:3.3, c:4.5, g:2.5 },
  { id:"queijo_coalho_grelhado", name:"Queijo coalho grelhado", cat:"laticinio", kcal:320, p:22, c:1.5, g:25 },
  { id:"leite_desnatado_po", name:"Leite em pó desnatado", cat:"laticinio", kcal:362, p:36, c:52, g:0.7 },

  // ---------- OUTROS (pratos prontos, doces, bebidas) ----------
  { id:"coxinha_frita", name:"Coxinha de frango frita", cat:"outro", kcal:283, p:9.6, c:34.5, g:11.8 },
  { id:"empada_frango", name:"Empada de frango assada", cat:"outro", kcal:358, p:6.9, c:47.5, g:15.6 },
  { id:"quibe_assado", name:"Quibe assado", cat:"outro", kcal:136, p:14.6, c:12.9, g:2.7 },
  { id:"pastel_carne_frito", name:"Pastel de carne frito", cat:"outro", kcal:388, p:8, c:43.8, g:20.1 },
  { id:"feijoada_completa", name:"Feijoada", cat:"outro", kcal:117, p:8.7, c:11.6, g:6.5 },
  { id:"brigadeiro", name:"Brigadeiro", cat:"outro", kcal:411, p:4.5, c:63, g:16 },
  { id:"beijinho", name:"Beijinho (doce de coco)", cat:"outro", kcal:390, p:3, c:60, g:15 },
  { id:"pudim_leite", name:"Pudim de leite condensado", cat:"outro", kcal:227, p:5, c:35, g:7 },
  { id:"pacoca", name:"Paçoca (doce de amendoim)", cat:"outro", kcal:468, p:15, c:52, g:23 },
  { id:"cocada", name:"Cocada", cat:"outro", kcal:384, p:3, c:60, g:15 },
  { id:"suco_laranja_natural", name:"Suco de laranja natural (sem açúcar)", cat:"outro", kcal:37, p:0.7, c:8.6, g:0.1 },
  { id:"refrigerante_cola", name:"Refrigerante tipo cola", cat:"outro", kcal:42, p:0, c:10.5, g:0 },

  // ================= +300 ALIMENTOS (3ª leva) =================
  // ---------- PROTEÍNAS ----------
  { id:"peru_assado_sem_pele", name:"Peru assado sem pele", cat:"proteina", kcal:165, p:29, c:0, g:4.5 },
  { id:"pato_assado_sem_pele", name:"Pato assado sem pele", cat:"proteina", kcal:201, p:23.5, c:0, g:11.2 },
  { id:"codorna_assada_inteira", name:"Codorna assada (inteira)", cat:"proteina", kcal:192, p:25, c:0, g:9.6 },
  { id:"coelho_assado", name:"Coelho assado", cat:"proteina", kcal:173, p:29, c:0, g:6.7 },
  { id:"carneiro_grelhado", name:"Carneiro grelhado", cat:"proteina", kcal:235, p:25, c:0, g:14.8 },
  { id:"carne_bode_assada", name:"Carne de bode assada", cat:"proteina", kcal:165, p:27, c:0, g:5.8 },
  { id:"buchada_bode", name:"Buchada de bode", cat:"proteina", kcal:196, p:15, c:8, g:12 },
  { id:"dourado_grelhado", name:"Dourado filé grelhado", cat:"proteina", kcal:95, p:20, c:0, g:1.2 },
  { id:"pintado_grelhado", name:"Pintado filé grelhado", cat:"proteina", kcal:105, p:19, c:0, g:2.8 },
  { id:"pirarucu_grelhado", name:"Pirarucu filé grelhado", cat:"proteina", kcal:92, p:20, c:0, g:0.9 },
  { id:"corvina_grelhada", name:"Corvina filé grelhado", cat:"proteina", kcal:89, p:18.7, c:0, g:1.5 },
  { id:"cacao_grelhado", name:"Cação grelhado", cat:"proteina", kcal:104, p:21, c:0, g:1.9 },
  { id:"badejo_grelhado", name:"Badejo filé grelhado", cat:"proteina", kcal:96, p:19.5, c:0, g:1.7 },
  { id:"tainha_grelhada", name:"Tainha grelhada", cat:"proteina", kcal:118, p:19, c:0, g:4.2 },
  { id:"robalo_grelhado", name:"Robalo grelhado", cat:"proteina", kcal:99, p:20, c:0, g:1.6 },
  { id:"linguado_grelhado", name:"Linguado grelhado", cat:"proteina", kcal:91, p:18.8, c:0, g:1.3 },
  { id:"curimata_frito", name:"Curimatã frito", cat:"proteina", kcal:175, p:18, c:6, g:9 },
  { id:"caranguejo_cozido", name:"Caranguejo cozido (carne)", cat:"proteina", kcal:87, p:18, c:0, g:1 },
  { id:"siri_desfiado_cozido", name:"Siri desfiado cozido", cat:"proteina", kcal:90, p:19, c:1, g:1 },
  { id:"marisco_cozido", name:"Marisco/mexilhão cozido", cat:"proteina", kcal:86, p:14, c:3.7, g:2.2 },
  { id:"ostra_crua", name:"Ostra crua", cat:"proteina", kcal:68, p:7, c:3.9, g:2.5 },
  { id:"sarapatel", name:"Sarapatel", cat:"proteina", kcal:220, p:16, c:4, g:15 },
  { id:"mocoto_cozido", name:"Mocotó cozido", cat:"proteina", kcal:100, p:20, c:0, g:2 },
  { id:"rabada_cozida", name:"Rabada cozida", cat:"proteina", kcal:235, p:22, c:0, g:16 },
  { id:"miolo_bovino_cru", name:"Miolo bovino cru", cat:"proteina", kcal:130, p:10.5, c:0, g:9.5 },
  { id:"coracao_galinha_grelhado", name:"Coração de galinha grelhado", cat:"proteina", kcal:195, p:21, c:0.4, g:11.7 },
  { id:"moela_galinha_cozida", name:"Moela de galinha cozida", cat:"proteina", kcal:120, p:22, c:0, g:3 },
  { id:"rim_bovino_cozido", name:"Rim bovino cozido", cat:"proteina", kcal:130, p:20, c:0, g:5 },
  { id:"drumette_frango_frito", name:"Drumette de asa de frango frito", cat:"proteina", kcal:260, p:24, c:8, g:15 },
  { id:"chester_assado_sem_pele", name:"Chester assado sem pele", cat:"proteina", kcal:155, p:24, c:0, g:6 },
  { id:"peru_lombo_assado", name:"Lombo de peru assado", cat:"proteina", kcal:135, p:25, c:0, g:3.5 },
  { id:"costela_bovina_assada", name:"Costela bovina assada", cat:"proteina", kcal:250, p:25, c:0, g:17 },
  { id:"picanha_grelhada", name:"Picanha grelhada", cat:"proteina", kcal:289, p:25, c:0, g:21 },
  { id:"cupim_assado", name:"Cupim assado", cat:"proteina", kcal:280, p:23, c:0, g:20 },
  { id:"contrafile_grelhado", name:"Contrafilé grelhado", cat:"proteina", kcal:210, p:26, c:0, g:11.4 },
  { id:"musculo_bovino_cozido", name:"Músculo bovino cozido", cat:"proteina", kcal:160, p:26, c:0, g:5.6 },
  { id:"frango_xadrez", name:"Frango xadrez (peito em cubos)", cat:"proteina", kcal:165, p:20, c:8, g:6 },
  { id:"carne_panela_ensopada", name:"Carne de panela ensopada", cat:"proteina", kcal:195, p:22, c:3, g:10 },
  { id:"escondidinho_carne_seca", name:"Escondidinho de carne seca", cat:"proteina", kcal:175, p:10, c:15, g:9 },
  { id:"estrogonofe_frango", name:"Estrogonofe de frango", cat:"proteina", kcal:190, p:14, c:8, g:11.5 },
  { id:"estrogonofe_carne", name:"Estrogonofe de carne", cat:"proteina", kcal:205, p:15, c:7, g:13 },
  { id:"almondega_molho", name:"Almôndega ao molho", cat:"proteina", kcal:155, p:12, c:6, g:9 },
  { id:"bife_milanesa", name:"Bife à milanesa", cat:"proteina", kcal:250, p:22, c:12, g:13 },
  { id:"kafta_grelhada", name:"Kafta grelhada", cat:"proteina", kcal:220, p:18, c:4, g:15 },
  { id:"galinha_caipira_cozida", name:"Galinha caipira cozida", cat:"proteina", kcal:190, p:25, c:0, g:9.5 },
  { id:"ovo_mexido_manteiga", name:"Ovo mexido com manteiga", cat:"proteina", kcal:180, p:12.5, c:1.5, g:14 },
  { id:"omelete_simples", name:"Omelete simples", cat:"proteina", kcal:154, p:10.8, c:1.5, g:11.7 },
  { id:"clara_ovo_pasteurizada", name:"Clara de ovo pasteurizada (líquida)", cat:"proteina", kcal:48, p:10.5, c:0.7, g:0 },
  { id:"whey_hidrolisado", name:"Whey protein hidrolisado (pó)", cat:"proteina", kcal:375, p:85, c:4, g:3 },
  { id:"barra_proteina_whey", name:"Barra de proteína (whey)", cat:"proteina", kcal:380, p:30, c:35, g:12, f:5 },
  { id:"dobradinha", name:"Dobradinha", cat:"proteina", kcal:125, p:19.8, c:0, g:4.4 },
  { id:"torresmo", name:"Torresmo", cat:"proteina", kcal:544, p:61.3, c:0, g:31.3 },

  // ---------- LEGUMINOSAS ----------
  { id:"feijao_preto_cru", name:"Feijão preto cru", cat:"leguminosa", kcal:341, p:21.9, c:60.9, g:1.3, f:14 },
  { id:"feijao_carioca_cru", name:"Feijão carioca cru", cat:"leguminosa", kcal:329, p:20.5, c:61.2, g:1.5, f:15.5 },
  { id:"lentilha_crua", name:"Lentilha crua", cat:"leguminosa", kcal:336, p:25.8, c:56.9, g:1.1, f:17 },
  { id:"grao_bico_cru", name:"Grão de bico cru", cat:"leguminosa", kcal:355, p:20.5, c:57.8, g:6, f:17.4 },
  { id:"ervilha_lata_drenada", name:"Ervilha em lata (drenada)", cat:"leguminosa", kcal:68, p:3.9, c:10.6, g:0.6, f:4.5 },
  { id:"ervilha_torta_cozida", name:"Ervilha torta cozida (vagem doce)", cat:"leguminosa", kcal:42, p:3, c:7.6, g:0.3, f:2.6 },
  { id:"feijao_guandu_cozido", name:"Feijão guandu cozido", cat:"leguminosa", kcal:121, p:7, c:20.2, g:0.6, f:6.4 },
  { id:"soja_grao_crua", name:"Soja em grão crua", cat:"leguminosa", kcal:446, p:36.5, c:30.2, g:19.9, f:9.3 },
  { id:"tremoco_conserva", name:"Tremoço em conserva", cat:"leguminosa", kcal:119, p:15.6, c:9.6, g:2.9, f:7.1 },
  { id:"fava_cozida", name:"Fava cozida", cat:"leguminosa", kcal:88, p:6.9, c:15.4, g:0.4, f:5.4 },
  { id:"feijao_manteiga_cozido", name:"Feijão manteiga cozido", cat:"leguminosa", kcal:88, p:5.5, c:16, g:0.3, f:6 },
  { id:"grao_bico_lata_drenado", name:"Grão de bico em lata (drenado)", cat:"leguminosa", kcal:139, p:7.9, c:22.5, g:2.6, f:6 },
  { id:"feijao_jalo_cozido", name:"Feijão jalo cozido", cat:"leguminosa", kcal:90, p:5.5, c:16.5, g:0.5, f:7 },
  { id:"feijao_roxinho_cozido", name:"Feijão roxinho cozido", cat:"leguminosa", kcal:90, p:5.7, c:16.8, g:0.4, f:6.5 },
  { id:"hummus_grao_bico", name:"Homus (pasta de grão de bico)", cat:"leguminosa", kcal:166, p:7.9, c:14.3, g:9.6, f:6 },

  // ---------- CARBOIDRATOS ----------
  { id:"pao_forma_tradicional", name:"Pão de forma tradicional", cat:"carboidrato", kcal:265, p:9, c:49, g:3.2, f:2.5 },
  { id:"pao_australiano", name:"Pão australiano", cat:"carboidrato", kcal:280, p:9, c:52, g:4 },
  { id:"pao_hamburguer", name:"Pão de hambúrguer", cat:"carboidrato", kcal:280, p:9, c:50, g:5 },
  { id:"pao_baguete", name:"Pão baguete", cat:"carboidrato", kcal:270, p:9, c:55, g:1.5 },
  { id:"croissant", name:"Croissant", cat:"carboidrato", kcal:406, p:8.2, c:45.8, g:21 },
  { id:"pao_doce", name:"Pão doce", cat:"carboidrato", kcal:300, p:7, c:58, g:4 },
  { id:"pao_de_leite", name:"Pão de leite", cat:"carboidrato", kcal:310, p:8, c:55, g:6 },
  { id:"wrap_tortilla_trigo", name:"Wrap (tortilla de trigo)", cat:"carboidrato", kcal:310, p:9, c:50, g:7 },
  { id:"trigo_grao_cozido", name:"Trigo em grão cozido", cat:"carboidrato", kcal:198, p:5.5, c:42, g:0.9, f:5 },
  { id:"cevada_cozida", name:"Cevada cozida", cat:"carboidrato", kcal:123, p:2.3, c:28.2, g:0.4, f:3.8 },
  { id:"painco_cozido", name:"Painço cozido (milheto)", cat:"carboidrato", kcal:119, p:3.5, c:23.7, g:1, f:1.3 },
  { id:"amaranto_cozido", name:"Amaranto cozido", cat:"carboidrato", kcal:102, p:3.8, c:18.7, g:1.6, f:2.1 },
  { id:"centeio_grao_cozido", name:"Centeio em grão cozido", cat:"carboidrato", kcal:83, p:2.7, c:17.7, g:0.7, f:3.5 },
  { id:"risoto_camarao", name:"Risoto de camarão", cat:"carboidrato", kcal:165, p:8, c:22, g:5 },
  { id:"yakisoba", name:"Yakisoba", cat:"carboidrato", kcal:120, p:4, c:18, g:3.5 },
  { id:"macarrao_alho_oleo", name:"Macarrão alho e óleo", cat:"carboidrato", kcal:175, p:5, c:28, g:5 },
  { id:"biscoito_agua_sal", name:"Biscoito água e sal", cat:"carboidrato", kcal:432, p:10, c:75, g:10 },
  { id:"biscoito_integral", name:"Biscoito integral", cat:"carboidrato", kcal:410, p:9, c:68, g:12, f:5 },
  { id:"torrada_integral", name:"Torrada integral", cat:"carboidrato", kcal:375, p:12, c:68, g:5, f:7 },
  { id:"grissini", name:"Grissini (palito italiano)", cat:"carboidrato", kcal:428, p:11, c:71, g:10 },
  { id:"cara_cozido", name:"Cará cozido", cat:"carboidrato", kcal:97, p:1.9, c:21, g:0.1, f:2 },
  { id:"mandioca_frita", name:"Mandioca frita", cat:"carboidrato", kcal:300, p:1.5, c:45, g:12 },
  { id:"cereal_matinal_acucarado", name:"Cereal matinal açucarado", cat:"carboidrato", kcal:380, p:5, c:85, g:2 },
  { id:"cereal_matinal_integral", name:"Cereal matinal integral", cat:"carboidrato", kcal:350, p:8, c:75, g:4, f:8 },
  { id:"barra_cereal", name:"Barra de cereal", cat:"carboidrato", kcal:390, p:7, c:72, g:8, f:4 },
  { id:"sonho_doce", name:"Sonho (doce recheado)", cat:"carboidrato", kcal:330, p:6, c:45, g:15 },
  { id:"rosquinha", name:"Rosquinha", cat:"carboidrato", kcal:420, p:7, c:60, g:17 },
  { id:"waffle", name:"Waffle", cat:"carboidrato", kcal:291, p:7.9, c:32.9, g:14.1 },
  { id:"panqueca_americana", name:"Panqueca americana", cat:"carboidrato", kcal:227, p:6.4, c:28, g:9.6 },
  { id:"crepioca", name:"Crepioca", cat:"carboidrato", kcal:155, p:8, c:18, g:6 },
  { id:"bolo_cenoura", name:"Bolo de cenoura", cat:"carboidrato", kcal:340, p:5, c:52, g:13 },
  { id:"bolo_laranja", name:"Bolo de laranja", cat:"carboidrato", kcal:300, p:5, c:55, g:7 },
  { id:"pao_de_mel", name:"Pão de mel", cat:"carboidrato", kcal:350, p:5, c:65, g:8 },
  { id:"batata_yacon_crua", name:"Batata yacon crua", cat:"carboidrato", kcal:54, p:0.4, c:12.8, g:0.1, f:2.2 },
  { id:"canjica_branca_cozida", name:"Canjica branca cozida", cat:"carboidrato", kcal:105, p:2.5, c:22, g:0.8, f:2 },
  { id:"pipoca_doce", name:"Pipoca doce (com açúcar)", cat:"carboidrato", kcal:480, p:6, c:90, g:10 },
  { id:"bolacha_amanteigada", name:"Bolacha amanteigada", cat:"carboidrato", kcal:470, p:6, c:68, g:20 },
  { id:"pao_forma_light", name:"Pão de forma light", cat:"carboidrato", kcal:230, p:10, c:42, g:2, f:6 },
  { id:"cuscuz_leite", name:"Cuscuz nordestino com leite", cat:"carboidrato", kcal:130, p:4, c:24, g:2 },
  { id:"beiju_tapioca", name:"Beiju (tapioca fina)", cat:"carboidrato", kcal:234, p:0.6, c:57, g:0.1 },
  { id:"farinha_mandioca_crua", name:"Farinha de mandioca crua", cat:"carboidrato", kcal:365, p:1.6, c:87.9, g:0.3, f:6.4 },
  { id:"farinha_aveia", name:"Farinha de aveia", cat:"carboidrato", kcal:393, p:13.4, c:67.7, g:7, f:7.5 },
  { id:"granola_proteica", name:"Granola proteica", cat:"carboidrato", kcal:430, p:18, c:55, g:15, f:8 },
  { id:"mingau_milho_cremoso", name:"Mingau de milho (creme de milho)", cat:"carboidrato", kcal:75, p:1.5, c:17, g:0.2 },
  { id:"nhoque_mandioquinha", name:"Nhoque de mandioquinha", cat:"carboidrato", kcal:125, p:2.8, c:27, g:0.9 },
  { id:"batata_doce_frita", name:"Batata doce frita", cat:"carboidrato", kcal:180, p:2, c:30, g:6 },
  { id:"pao_pita_integral", name:"Pão pita integral", cat:"carboidrato", kcal:265, p:10, c:50, g:2.5, f:7.5 },
  { id:"rosca_doce_coco", name:"Rosca doce de coco", cat:"carboidrato", kcal:375, p:6, c:60, g:13 },
  { id:"biscoito_polvilho", name:"Biscoito de polvilho", cat:"carboidrato", kcal:470, p:3, c:75, g:17 },
  { id:"pao_de_alho", name:"Pão de alho", cat:"carboidrato", kcal:330, p:7, c:42, g:15 },
  { id:"macarrao_molho_branco", name:"Macarrão ao molho branco", cat:"carboidrato", kcal:165, p:5, c:20, g:7 },
  { id:"lasanha_bolonhesa", name:"Lasanha à bolonhesa", cat:"carboidrato", kcal:155, p:8, c:15, g:7 },
  { id:"arroz_a_grega", name:"Arroz à grega", cat:"carboidrato", kcal:145, p:3, c:26, g:3 },
  { id:"bolo_milho_verde", name:"Bolo de milho verde", cat:"carboidrato", kcal:260, p:5, c:42, g:8 },
  { id:"torta_salgada_massa", name:"Torta salgada (massa, sem recheio)", cat:"carboidrato", kcal:290, p:6, c:30, g:16 },
  { id:"pinhao_cozido", name:"Pinhão cozido", cat:"carboidrato", kcal:152, p:3.1, c:34.4, g:0.8, f:4.5 },
  { id:"doce_leite_cremoso", name:"Doce de leite cremoso", cat:"carboidrato", kcal:306, p:5.5, c:59.5, g:6 },

  // ---------- GORDURAS ----------
  { id:"amendoim_cru", name:"Amendoim cru (com pele)", cat:"gordura", kcal:544, p:25.8, c:20.3, g:43.9, f:8 },
  { id:"leite_coco", name:"Leite de coco", cat:"gordura", kcal:230, p:2.3, c:5.5, g:21.3, f:2.2 },
  { id:"creme_coco", name:"Creme de coco", cat:"gordura", kcal:330, p:3.4, c:6.7, g:32.8 },
  { id:"manteiga_amendoas", name:"Manteiga de amêndoas", cat:"gordura", kcal:614, p:21, c:18.8, g:55.5, f:10.3 },
  { id:"manteiga_ghee", name:"Manteiga ghee (clarificada)", cat:"gordura", kcal:900, p:0.3, c:0, g:99.8 },
  { id:"oleo_gergelim", name:"Óleo de gergelim", cat:"gordura", kcal:884, p:0, c:0, g:100 },
  { id:"tahine_pasta_gergelim", name:"Tahine (pasta de gergelim)", cat:"gordura", kcal:595, p:17, c:21, g:53, f:9.3 },
  { id:"semente_abobora", name:"Semente de abóbora torrada", cat:"gordura", kcal:559, p:30.2, c:10.7, g:49, f:6 },
  { id:"semente_gergelim", name:"Semente de gergelim", cat:"gordura", kcal:573, p:17.7, c:23.4, g:49.7, f:11.8 },
  { id:"castanha_baru", name:"Castanha de baru", cat:"gordura", kcal:452, p:25.9, c:31.5, g:38.3, f:8 },
  { id:"manteiga_sem_sal", name:"Manteiga sem sal", cat:"gordura", kcal:726, p:0.5, c:0.1, g:82 },
  { id:"banha_porco", name:"Banha de porco", cat:"gordura", kcal:902, p:0, c:0, g:100 },
  { id:"oleo_palma_dende", name:"Óleo de palma (dendê)", cat:"gordura", kcal:884, p:0, c:0, g:100 },
  { id:"oleo_linhaca", name:"Óleo de linhaça", cat:"gordura", kcal:884, p:0, c:0, g:100 },
  { id:"creme_avela_cacau", name:"Creme de avelã com cacau", cat:"gordura", kcal:539, p:6, c:58, g:31 },
  { id:"oleo_abacate", name:"Óleo de abacate", cat:"gordura", kcal:884, p:0, c:0, g:100 },
  { id:"gordura_vegetal_hidrogenada", name:"Gordura vegetal hidrogenada", cat:"gordura", kcal:884, p:0, c:0, g:100 },
  { id:"castanha_mista", name:"Castanha mista (mix de castanhas)", cat:"gordura", kcal:600, p:18, c:20, g:52, f:7 },
  { id:"sebo_bovino", name:"Sebo bovino", cat:"gordura", kcal:854, p:1.5, c:0, g:94 },
  { id:"pasta_gergelim_negro", name:"Pasta de gergelim negro", cat:"gordura", kcal:582, p:18, c:20, g:52, f:12 },

  // ---------- FRUTAS ----------
  { id:"acerola_crua", name:"Acerola crua", cat:"fruta", kcal:33, p:0.9, c:7.7, g:0.2, f:1.9 },
  { id:"caja_polpa", name:"Cajá polpa", cat:"fruta", kcal:39, p:0.9, c:9.7, g:0.2, f:1.3 },
  { id:"umbu_cru", name:"Umbu cru", cat:"fruta", kcal:37, p:0.8, c:9.1, g:0.2, f:1 },
  { id:"sapoti_cru", name:"Sapoti cru", cat:"fruta", kcal:83, p:0.4, c:20, g:1.1, f:5.3 },
  { id:"araca_cru", name:"Araçá cru", cat:"fruta", kcal:36, p:0.7, c:8.7, g:0.3, f:3.2 },
  { id:"mangaba_crua", name:"Mangaba crua", cat:"fruta", kcal:47, p:0.9, c:11.2, g:0.4, f:2 },
  { id:"murici_cru", name:"Murici cru", cat:"fruta", kcal:87, p:1, c:19.7, g:1.2, f:4 },
  { id:"lichia_crua", name:"Lichia crua", cat:"fruta", kcal:66, p:0.8, c:16.5, g:0.4, f:1.3 },
  { id:"rambutan_cru", name:"Rambutan cru", cat:"fruta", kcal:68, p:0.9, c:16.5, g:0.2 },
  { id:"melao_cru", name:"Melão cru", cat:"fruta", kcal:29, p:0.7, c:7.5, g:0.1, f:0.6 },
  { id:"melao_honeydew", name:"Melão honeydew cru", cat:"fruta", kcal:36, p:0.5, c:9.1, g:0.1, f:0.8 },
  { id:"nectarina_crua", name:"Nectarina crua", cat:"fruta", kcal:44, p:1.1, c:10.6, g:0.3, f:1.7 },
  { id:"physalis_crua", name:"Physalis crua", cat:"fruta", kcal:53, p:1.9, c:11.2, g:0.7, f:3 },
  { id:"tangerina_ponkan", name:"Tangerina ponkan crua", cat:"fruta", kcal:46, p:0.8, c:11.7, g:0.1, f:2.9 },
  { id:"abacaxi_havai", name:"Abacaxi havaí cru", cat:"fruta", kcal:50, p:0.5, c:13, g:0.1, f:1.2 },
  { id:"banana_nanica", name:"Banana nanica crua", cat:"fruta", kcal:92, p:1.4, c:23.8, g:0.1, f:2 },
  { id:"banana_maca", name:"Banana maçã crua", cat:"fruta", kcal:87, p:1.2, c:22.3, g:0.1, f:2.6 },
  { id:"banana_da_terra_frita", name:"Banana-da-terra frita", cat:"fruta", kcal:207, p:1.6, c:37, g:6.5 },
  { id:"maca_verde", name:"Maçã verde crua", cat:"fruta", kcal:52, p:0.3, c:13.8, g:0.2, f:2.4 },
  { id:"laranja_lima", name:"Laranja lima crua", cat:"fruta", kcal:37, p:1, c:9.1, g:0.1, f:2.4 },
  { id:"laranja_bahia", name:"Laranja bahia crua", cat:"fruta", kcal:49, p:1, c:12.3, g:0.2, f:1 },
  { id:"uva_italia", name:"Uva itália crua", cat:"fruta", kcal:58, p:0.6, c:15.3, g:0.3, f:0.7 },
  { id:"uva_passa", name:"Uva passa", cat:"fruta", kcal:299, p:2.9, c:79.2, g:0.5, f:4 },
  { id:"figo_cru", name:"Figo cru", cat:"fruta", kcal:41, p:0.8, c:9.5, g:0.2, f:2 },
  { id:"figo_seco", name:"Figo seco", cat:"fruta", kcal:249, p:3.3, c:63.9, g:0.9, f:9.6 },
  { id:"pera_asiatica", name:"Pera asiática crua", cat:"fruta", kcal:42, p:0.5, c:10.6, g:0.2, f:2 },
  { id:"morango_congelado", name:"Morango polpa congelada", cat:"fruta", kcal:33, p:0.7, c:7.7, g:0.2, f:1.6 },
  { id:"manga_polpa_congelada", name:"Manga polpa congelada", cat:"fruta", kcal:51, p:0.4, c:12.8, g:0.2, f:1.3 },
  { id:"maracuja_polpa_congelada", name:"Maracujá polpa congelada", cat:"fruta", kcal:60, p:1.8, c:12.3, g:0.6 },
  { id:"abacaxi_desidratado", name:"Abacaxi desidratado", cat:"fruta", kcal:328, p:2.9, c:81, g:0.5, f:8 },
  { id:"banana_passa", name:"Banana passa (desidratada)", cat:"fruta", kcal:299, p:3.3, c:73.5, g:1.8, f:7.7 },
  { id:"coco_seco_ralado", name:"Coco seco ralado (sem açúcar)", cat:"fruta", kcal:660, p:6.9, c:23.7, g:64.5, f:16.3 },
  { id:"coco_ralado_acucarado", name:"Coco ralado com açúcar", cat:"fruta", kcal:592, p:3.6, c:56.8, g:39.1, f:9 },
  { id:"jaboticaba_polpa", name:"Jabuticaba polpa", cat:"fruta", kcal:58, p:0.6, c:15.3, g:0.1, f:2.3 },
  { id:"graviola_suco", name:"Suco de graviola", cat:"fruta", kcal:47, p:0.5, c:12, g:0.1 },
  { id:"acai_polpa_pura", name:"Açaí polpa pura (sem xarope)", cat:"fruta", kcal:58, p:0.8, c:6.2, g:3.9, f:2.6 },
  { id:"caja_manga_crua", name:"Cajá-manga crua", cat:"fruta", kcal:47, p:0.6, c:12.2, g:0.2, f:2 },
  { id:"pequi_polpa_cozida", name:"Pequi polpa cozida", cat:"fruta", kcal:225, p:2.3, c:15.4, g:18.1, f:8 },
  { id:"pitanga_polpa", name:"Pitanga polpa", cat:"fruta", kcal:41, p:0.8, c:9.9, g:0.2, f:1.2 },
  { id:"seriguela_crua", name:"Seriguela crua", cat:"fruta", kcal:60, p:0.8, c:15, g:0.2, f:1.5 },
  { id:"bacuri_polpa", name:"Bacuri polpa", cat:"fruta", kcal:56, p:0.7, c:13.7, g:0.4 },
  { id:"biriba_crua", name:"Biribá crua", cat:"fruta", kcal:70, p:1.3, c:17.9, g:0.3 },
  { id:"caqui_rama_forte", name:"Caqui rama-forte cru", cat:"fruta", kcal:65, p:0.6, c:16.8, g:0.2, f:3.2 },
  { id:"morango_desidratado", name:"Morango desidratado", cat:"fruta", kcal:334, p:3.9, c:75, g:2.5, f:8 },
  { id:"manga_haden", name:"Manga haden crua", cat:"fruta", kcal:62, p:0.5, c:16, g:0.2, f:1.8 },
  { id:"manga_tommy", name:"Manga tommy crua", cat:"fruta", kcal:60, p:0.6, c:15.5, g:0.3, f:1.6 },
  { id:"melancia_sem_sementes", name:"Melancia sem sementes crua", cat:"fruta", kcal:31, p:0.6, c:8, g:0.2 },
  { id:"laranja_suco_industrializado", name:"Suco de laranja industrializado (caixinha)", cat:"fruta", kcal:45, p:0.5, c:11, g:0.1 },
  { id:"suco_uva_integral", name:"Suco de uva integral", cat:"fruta", kcal:60, p:0.3, c:14.9, g:0 },
  { id:"suco_caju", name:"Suco de caju", cat:"fruta", kcal:45, p:0.1, c:11.2, g:0.1 },
  { id:"suco_manga_industrializado", name:"Suco de manga industrializado", cat:"fruta", kcal:54, p:0.2, c:13.4, g:0.1 },
  { id:"suco_acerola_industrializado", name:"Suco de acerola industrializado", cat:"fruta", kcal:23, p:0.2, c:5.7, g:0 },

  // ---------- VEGETAIS ----------
  { id:"abobora_crua", name:"Abóbora crua", cat:"vegetal", kcal:38, p:1.4, c:9.3, g:0.1, f:1.5 },
  { id:"abobrinha_crua", name:"Abobrinha crua", cat:"vegetal", kcal:19, p:1.4, c:4.1, g:0.1, f:1.5 },
  { id:"acelga_crua", name:"Acelga crua", cat:"vegetal", kcal:19, p:1.8, c:3.7, g:0.2, f:1.6 },
  { id:"aipo_cru", name:"Aipo (salsão) cru", cat:"vegetal", kcal:16, p:0.7, c:3.6, g:0.2, f:1.7 },
  { id:"alho_cru", name:"Alho cru", cat:"vegetal", kcal:113, p:7.1, c:23.9, g:0.3, f:4.3 },
  { id:"alho_poro_cru", name:"Alho-poró cru", cat:"vegetal", kcal:29, p:1.3, c:6.6, g:0.1, f:1.9 },
  { id:"almeirao_cru", name:"Almeirão cru", cat:"vegetal", kcal:22, p:2.1, c:3.9, g:0.4, f:2.4 },
  { id:"berinjela_grelhada", name:"Berinjela grelhada", cat:"vegetal", kcal:28, p:1, c:6.2, g:0.4, f:2.5 },
  { id:"broccolis_cru", name:"Brócolis cru", cat:"vegetal", kcal:32, p:2.6, c:5.2, g:0.6, f:3 },
  { id:"cebola_roxa_crua", name:"Cebola roxa crua", cat:"vegetal", kcal:35, p:1.1, c:8.3, g:0.1, f:1.6 },
  { id:"cebolinha_crua", name:"Cebolinha crua", cat:"vegetal", kcal:23, p:1.9, c:3.4, g:0.5, f:1.7 },
  { id:"cenoura_cozida", name:"Cenoura cozida", cat:"vegetal", kcal:32, p:0.7, c:7.7, g:0.2, f:3.2 },
  { id:"chicoria_crua", name:"Chicória crua", cat:"vegetal", kcal:23, p:1.7, c:4.7, g:0.3, f:4 },
  { id:"couve_flor_cozida", name:"Couve-flor cozida", cat:"vegetal", kcal:22, p:1.8, c:4.5, g:0.1, f:2.4 },
  { id:"couve_flor_crua", name:"Couve-flor crua", cat:"vegetal", kcal:25, p:2, c:5, g:0.3, f:2.5 },
  { id:"escarola_crua", name:"Escarola crua", cat:"vegetal", kcal:17, p:1.3, c:3.4, g:0.2, f:2.9 },
  { id:"espinafre_cru", name:"Espinafre cru", cat:"vegetal", kcal:16, p:2.9, c:2.6, g:0.4, f:2.6 },
  { id:"gengibre_cru", name:"Gengibre cru", cat:"vegetal", kcal:80, p:1.8, c:17.8, g:0.8, f:2 },
  { id:"pepino_japones", name:"Pepino japonês cru", cat:"vegetal", kcal:12, p:0.7, c:2.5, g:0.1 },
  { id:"pimentao_amarelo", name:"Pimentão amarelo cru", cat:"vegetal", kcal:27, p:1, c:6.3, g:0.2, f:1.6 },
  { id:"pimentao_verde", name:"Pimentão verde cru", cat:"vegetal", kcal:19, p:1.1, c:4.6, g:0.2, f:2.2 },
  { id:"repolho_roxo_cru", name:"Repolho roxo cru", cat:"vegetal", kcal:31, p:1.3, c:7.4, g:0.1, f:2.1 },
  { id:"repolho_cozido", name:"Repolho cozido", cat:"vegetal", kcal:20, p:1, c:4.6, g:0.1, f:1.9 },
  { id:"salsa_crua", name:"Salsa crua", cat:"vegetal", kcal:36, p:3, c:6.3, g:0.8, f:3.3 },
  { id:"tomate_cereja", name:"Tomate cereja cru", cat:"vegetal", kcal:20, p:1, c:4.3, g:0.2, f:1.4 },
  { id:"vagem_refogada", name:"Vagem refogada", cat:"vegetal", kcal:35, p:1.9, c:5.8, g:1.2, f:2.3 },
  { id:"quiabo_cru", name:"Quiabo cru", cat:"vegetal", kcal:31, p:2, c:6.7, g:0.2, f:3.9 },
  { id:"maxixe_cru", name:"Maxixe cru", cat:"vegetal", kcal:14, p:1.1, c:3, g:0.1, f:1.1 },
  { id:"taioba_refogada", name:"Taioba refogada", cat:"vegetal", kcal:32, p:2.2, c:5.5, g:0.5, f:2.9 },
  { id:"couve_flor_gratinada", name:"Couve-flor gratinada", cat:"vegetal", kcal:95, p:5, c:8, g:5.5 },
  { id:"batata_frita_palito", name:"Batata palha", cat:"vegetal", kcal:502, p:5.9, c:50, g:31 },
  { id:"champignon_conserva", name:"Champignon em conserva", cat:"vegetal", kcal:19, p:2.5, c:2.6, g:0.3 },
  { id:"milho_lata_drenado", name:"Milho em lata (drenado)", cat:"vegetal", kcal:98, p:3, c:20.6, g:1.3, f:2 },
  { id:"seleta_legumes", name:"Seleta de legumes cozida", cat:"vegetal", kcal:62, p:1.9, c:11.3, g:1.1, f:2.8 },

  // ---------- LATICÍNIOS ----------
  { id:"queijo_minas_curado", name:"Queijo minas padrão (curado)", cat:"laticinio", kcal:341, p:24.3, c:2.6, g:26 },
  { id:"queijo_coalho_cru", name:"Queijo coalho cru", cat:"laticinio", kcal:290, p:20, c:1.6, g:22.6 },
  { id:"queijo_brie", name:"Queijo brie", cat:"laticinio", kcal:334, p:20.8, c:0.5, g:27.7 },
  { id:"queijo_gorgonzola", name:"Queijo gorgonzola", cat:"laticinio", kcal:353, p:21.4, c:2.3, g:28.7 },
  { id:"cream_cheese", name:"Cream cheese", cat:"laticinio", kcal:342, p:5.9, c:4.1, g:34.2 },
  { id:"manteiga_com_sal", name:"Manteiga com sal", cat:"laticinio", kcal:717, p:0.6, c:0.1, g:81 },
  { id:"iogurte_grego_frutas", name:"Iogurte grego sabor frutas vermelhas", cat:"laticinio", kcal:112, p:7.5, c:13.4, g:3.2 },
  { id:"leite_semidesnatado", name:"Leite semidesnatado", cat:"laticinio", kcal:46, p:3.2, c:4.7, g:1.6 },
  { id:"queijo_minas_meia_cura", name:"Queijo minas meia cura", cat:"laticinio", kcal:280, p:20, c:2, g:21 },
  { id:"queijo_reino", name:"Queijo do reino", cat:"laticinio", kcal:375, p:24.9, c:1.4, g:30.2 },
  { id:"iogurte_skyr", name:"Iogurte skyr natural", cat:"laticinio", kcal:63, p:11, c:4, g:0.2 },
  { id:"leite_amendoas", name:"Leite de amêndoas (sem açúcar)", cat:"laticinio", kcal:17, p:0.6, c:1.5, g:1.2 },
  { id:"leite_aveia", name:"Leite de aveia (sem açúcar)", cat:"laticinio", kcal:47, p:1, c:7.5, g:1.5 },
  { id:"nata_creme_leite_fresco", name:"Nata (creme de leite fresco)", cat:"laticinio", kcal:292, p:2.2, c:3.4, g:30.4 },
  { id:"queijo_minas_light", name:"Queijo minas frescal light", cat:"laticinio", kcal:180, p:18, c:3, g:10 },
  { id:"requeijao_light", name:"Requeijão light", cat:"laticinio", kcal:172, p:10.4, c:4.5, g:12.6 },
  { id:"leite_condensado_light", name:"Leite condensado light/desnatado", cat:"laticinio", kcal:280, p:8, c:56, g:2 },
  { id:"iogurte_natural_desnatado_light", name:"Iogurte natural light", cat:"laticinio", kcal:38, p:4, c:4.5, g:0.5 },
  { id:"queijo_mussarela_light", name:"Queijo muçarela light", cat:"laticinio", kcal:255, p:28, c:3, g:15 },
  { id:"bebida_lactea_chocolate", name:"Bebida láctea sabor chocolate", cat:"laticinio", kcal:65, p:1.6, c:12.5, g:1.1 },

  // ---------- OUTROS (pratos, doces, bebidas) ----------
  { id:"pizza_mussarela_fatia", name:"Pizza de mussarela (fatia)", cat:"outro", kcal:260, p:12, c:30, g:10 },
  { id:"pizza_calabresa_fatia", name:"Pizza de calabresa (fatia)", cat:"outro", kcal:275, p:13, c:29, g:12.5 },
  { id:"pizza_portuguesa_fatia", name:"Pizza portuguesa (fatia)", cat:"outro", kcal:250, p:12, c:28, g:10 },
  { id:"hamburguer_artesanal_simples", name:"Hambúrguer artesanal simples", cat:"outro", kcal:280, p:17, c:20, g:15 },
  { id:"hamburguer_com_queijo", name:"Hambúrguer com queijo", cat:"outro", kcal:310, p:18, c:21, g:18 },
  { id:"batata_frita_fast_food", name:"Batata frita de fast-food", cat:"outro", kcal:312, p:3.4, c:41, g:15 },
  { id:"nuggets_frango", name:"Nuggets de frango", cat:"outro", kcal:296, p:14.5, c:16, g:19.5 },
  { id:"cachorro_quente_completo", name:"Cachorro-quente completo", cat:"outro", kcal:250, p:9, c:24, g:13 },
  { id:"sanduiche_natural", name:"Sanduíche natural", cat:"outro", kcal:210, p:9, c:24, g:9 },
  { id:"sushi_salmao", name:"Sushi de salmão (peça)", cat:"outro", kcal:150, p:6.5, c:24, g:2.8 },
  { id:"temaki_salmao", name:"Temaki de salmão", cat:"outro", kcal:170, p:6, c:26, g:4 },
  { id:"hot_roll", name:"Hot roll (uramaki frito)", cat:"outro", kcal:230, p:7, c:24, g:11 },
  { id:"lasanha_pronta_industrializada", name:"Lasanha congelada industrializada", cat:"outro", kcal:145, p:6.5, c:15, g:6.5 },
  { id:"nachos_queijo", name:"Nachos com queijo", cat:"outro", kcal:346, p:7, c:36, g:19 },
  { id:"taco_carne", name:"Taco de carne", cat:"outro", kcal:210, p:9, c:20, g:10.5 },
  { id:"burrito_frango", name:"Burrito de frango", cat:"outro", kcal:200, p:10, c:24, g:7 },
  { id:"moqueca_peixe", name:"Moqueca de peixe", cat:"outro", kcal:132, p:18.6, c:1.5, g:4.6, f:1.4 },
  { id:"moqueca_camarao", name:"Moqueca de camarão", cat:"outro", kcal:145, p:16, c:3, g:7 },
  { id:"baiao_de_dois", name:"Baião de dois", cat:"outro", kcal:180, p:8, c:26, g:5 },
  { id:"galinhada", name:"Galinhada", cat:"outro", kcal:160, p:9, c:20, g:5 },
  { id:"arroz_carreteiro", name:"Arroz de carreteiro", cat:"outro", kcal:195, p:10, c:22, g:8 },
  { id:"tutu_feijao", name:"Tutu de feijão", cat:"outro", kcal:145, p:6, c:20, g:4.5 },
  { id:"angu_milho", name:"Angu de milho", cat:"outro", kcal:65, p:1.2, c:14, g:0.3 },
  { id:"farofa_banana", name:"Farofa de banana", cat:"outro", kcal:310, p:2.5, c:58, g:8 },
  { id:"vaca_atolada", name:"Vaca atolada", cat:"outro", kcal:170, p:12, c:12, g:9 },
  { id:"panelada", name:"Panelada", cat:"outro", kcal:150, p:14, c:5, g:8 },
  { id:"acaraje", name:"Acarajé", cat:"outro", kcal:290, p:8, c:20, g:20 },
  { id:"caruru", name:"Caruru", cat:"outro", kcal:110, p:5, c:8, g:7 },
  { id:"bobo_camarao", name:"Bobó de camarão", cat:"outro", kcal:150, p:8, c:14, g:7.5 },
  { id:"manicoba", name:"Maniçoba", cat:"outro", kcal:160, p:12, c:6, g:10 },
  { id:"tacaca", name:"Tacacá", cat:"outro", kcal:55, p:3, c:6, g:2 },
  { id:"chocolate_amargo", name:"Chocolate amargo (70% cacau)", cat:"outro", kcal:598, p:7.8, c:45.9, g:42.6, f:10.9 },
  { id:"chocolate_branco", name:"Chocolate branco", cat:"outro", kcal:539, p:5.9, c:59.2, g:30.9 },
  { id:"chocolate_castanha_para", name:"Chocolate ao leite com castanha-do-pará", cat:"outro", kcal:559, p:7.4, c:55.4, g:34.2 },
  { id:"bala_goma", name:"Bala de goma", cat:"outro", kcal:343, p:0, c:85, g:0 },
  { id:"pe_de_moleque", name:"Pé-de-moleque", cat:"outro", kcal:471, p:11, c:53, g:24 },
  { id:"bombom_chocolate", name:"Bombom de chocolate", cat:"outro", kcal:495, p:5, c:60, g:26 },
  { id:"sorvete_creme", name:"Sorvete de creme", cat:"outro", kcal:207, p:3.5, c:23.6, g:11 },
  { id:"sorvete_chocolate", name:"Sorvete de chocolate", cat:"outro", kcal:216, p:3.8, c:28, g:11 },
  { id:"picole_fruta", name:"Picolé de fruta", cat:"outro", kcal:75, p:0.5, c:18, g:0.1 },
  { id:"picole_chocolate", name:"Picolé de chocolate (com cobertura)", cat:"outro", kcal:245, p:3, c:26, g:14 },
  { id:"acai_tigela_completa", name:"Açaí na tigela (com granola e banana)", cat:"outro", kcal:150, p:2, c:24, g:5 },
  { id:"cerveja_pilsen", name:"Cerveja pilsen", cat:"outro", kcal:42, p:0.5, c:3.2, g:0 },
  { id:"vinho_tinto_seco", name:"Vinho tinto seco", cat:"outro", kcal:85, p:0.1, c:2.6, g:0 },
  { id:"vinho_branco_seco", name:"Vinho branco seco", cat:"outro", kcal:82, p:0.1, c:2.6, g:0 },
  { id:"refrigerante_guarana", name:"Refrigerante de guaraná", cat:"outro", kcal:40, p:0, c:10.3, g:0 },
  { id:"refrigerante_laranja", name:"Refrigerante sabor laranja", cat:"outro", kcal:48, p:0, c:12.4, g:0 },
  { id:"cha_mate_sem_acucar", name:"Chá mate (sem açúcar)", cat:"outro", kcal:2, p:0, c:0.3, g:0 },
  { id:"cha_verde_sem_acucar", name:"Chá verde (sem açúcar)", cat:"outro", kcal:1, p:0, c:0.2, g:0 },
  { id:"isotonico", name:"Isotônico esportivo", cat:"outro", kcal:24, p:0, c:6, g:0 },
  { id:"energetico_lata", name:"Energético (lata)", cat:"outro", kcal:45, p:0, c:11, g:0 },
  { id:"cafe_com_leite_acucar", name:"Café com leite e açúcar", cat:"outro", kcal:55, p:1.9, c:8.6, g:1.6 },
  { id:"achocolatado_po", name:"Achocolatado em pó", cat:"outro", kcal:376, p:4, c:87, g:2 },
  { id:"suco_polpa_industrializado", name:"Suco de polpa industrializado (adoçado)", cat:"outro", kcal:52, p:0.1, c:13, g:0 },
  { id:"agua_tonica", name:"Água tônica", cat:"outro", kcal:34, p:0, c:8.8, g:0 },
  { id:"limonada_acucar", name:"Limonada com açúcar", cat:"outro", kcal:40, p:0.1, c:10.2, g:0 },
  { id:"vitamina_banana_leite", name:"Vitamina de banana com leite", cat:"outro", kcal:95, p:3.2, c:16.5, g:2.3 },
  { id:"smoothie_frutas_vermelhas", name:"Smoothie de frutas vermelhas", cat:"outro", kcal:78, p:1.2, c:18, g:0.5 }
];
